// NOTE: this pattern is inspired by https://github.com/payloadcms/payload/blob/main/test/generateDatabaseAdapter.ts

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const filename = fileURLToPath(import.meta.url)
const dirname = path.dirname(filename)

export type DatabaseAdapter = 'mongodb' | 'sqlite'

const databaseAdapters: Record<DatabaseAdapter, string> = {
  mongodb: `
import { mongooseAdapter } from '@payloadcms/db-mongodb'

export const databaseAdapter = mongooseAdapter({
  url: process.env.MONGODB_URL!,
})
`,
  sqlite: `
import { sqliteAdapter } from '@payloadcms/db-sqlite'

export const databaseAdapter = sqliteAdapter({
  client: {
    url: process.env.SQLITE_URL!,
  },
})
`,
}

/**
 * Generates a database adapter file based on the PAYLOAD_DATABASE environment variable.
 * This allows the same tests to run against different databases without code duplication.
 */
export function generateDatabaseAdapter(dbAdapter: DatabaseAdapter = 'mongodb'): string {
  const adapterCode = databaseAdapters[dbAdapter]
  if (!adapterCode) {
    throw new Error(
      `Unknown database adapter: ${dbAdapter}. Valid options are: ${Object.keys(databaseAdapters).join(', ')}`,
    )
  }

  const outputPath = path.resolve(dirname, 'databaseAdapter.ts')

  fs.writeFileSync(
    outputPath,
    `// DO NOT MODIFY. This file is automatically generated.
// Generated for database: ${dbAdapter}
${adapterCode}
`,
  )

  console.log(
    `\n##############################\n## Generated database adapter for: ${dbAdapter} ##\n##############################\n`,
  )
  return adapterCode
}
