import payload, { CollectionSlug, SanitizedConfig } from 'payload'
import { afterAll, beforeAll, beforeEach, describe, expect, test } from 'vitest'
import { clearPathCache, findPageByPath } from '@jhb.software/payload-pages-plugin'
import config from './src/payload.config'
import type { Config } from 'payload/generated-types'

type DefaultIDType = Config['db']['defaultIDType']

/**
 * Empty virtual fields that are generated by the plugin.
 * Spread this into data objects when creating documents to satisfy TypeScript.
 */
const virtualFields = {
  breadcrumbs: [],
  meta: { alternatePaths: [] },
  path: '',
}

beforeAll(async () => {
  await payload.init({
    config: config,
  })

  await deleteAllCollections(config, ['users'])
})

afterAll(async () => {
  await deleteAllCollections(config)

  if (payload.db && typeof payload.db.destroy === 'function') {
    await payload.db.destroy()
  }
})

beforeEach(async () => {
  await deleteCollection('authors')
  await deleteCollection('pages')
  await clearPathCache(payload)
})

/** Returns all KV keys written by the pages plugin path cache. */
const pathCacheKeys = async () =>
  (await payload.kv.keys()).filter((key) => key.startsWith('payload-pages:'))

const createPage = async (data: {
  title: string
  slug: string
  parent?: DefaultIDType
  isRootPage?: boolean
  draft?: boolean
}) => {
  const { draft, ...rest } = data
  return await payload.create({
    collection: 'pages',
    locale: 'de',
    draft,
    data: {
      content: rest.title,
      // payload.create only publishes when _status is explicitly set
      _status: draft ? ('draft' as const) : ('published' as const),
      ...rest,
      ...virtualFields,
    },
  })
}

describe('findPageByPath resolves published pages', () => {
  test('resolves a nested page by its localized path', async () => {
    const parent = await createPage({ title: 'Parent', slug: 'parent' })
    const child = await createPage({ title: 'Child', slug: 'child', parent: parent.id })

    const result = await findPageByPath({ payload, path: '/de/parent/child' })

    expect(result).not.toBeNull()
    expect(result!.collection).toBe('pages')
    expect(result!.doc.id).toBe(child.id)
    expect(result!.doc.path).toBe('/de/parent/child')
  })

  test('resolves the root page', async () => {
    const rootPage = await createPage({ title: 'Root', slug: '', isRootPage: true })

    const result = await findPageByPath({ payload, path: '/de' })

    expect(result?.doc.id).toBe(rootPage.id)
    expect(result?.doc.path).toBe('/de')
  })

  test('returns null for a path that matches no page', async () => {
    await createPage({ title: 'Parent', slug: 'parent' })

    expect(await findPageByPath({ payload, path: '/de/unknown' })).toBeNull()
    // slug matches but full path does not
    expect(await findPageByPath({ payload, path: '/de/unknown/parent' })).toBeNull()
  })

  test('resolves pages of non-root page collections', async () => {
    const parent = await createPage({ title: 'Autoren', slug: 'autoren' })
    const author = await payload.create({
      collection: 'authors',
      locale: 'de',
      data: {
        name: 'Max Mustermann',
        content: 'Bio',
        slug: 'max-mustermann',
        parent: parent.id,
        ...virtualFields,
      },
    })

    const result = await findPageByPath({ payload, path: '/de/autoren/max-mustermann' })

    expect(result?.collection).toBe('authors')
    expect(result?.doc.id).toBe(author.id)
  })

  test('infers the locale from the path prefix', async () => {
    const page = await createPage({ title: 'Über uns', slug: 'ueber-uns' })
    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'en',
      data: { title: 'About us', slug: 'about-us', content: 'About us' },
    })

    const englishResult = await findPageByPath({ payload, path: '/en/about-us' })
    const germanResult = await findPageByPath({ payload, path: '/de/ueber-uns' })

    expect(englishResult?.doc.id).toBe(page.id)
    expect(englishResult?.doc.path).toBe('/en/about-us')
    expect(germanResult?.doc.id).toBe(page.id)
  })

  test('returns null when the page does not exist in the requested locale', async () => {
    await createPage({ title: 'Nur Deutsch', slug: 'nur-deutsch' })

    expect(await findPageByPath({ payload, path: '/en/nur-deutsch' })).toBeNull()
  })

  test('normalizes a trailing slash', async () => {
    const page = await createPage({ title: 'Parent', slug: 'parent' })

    const result = await findPageByPath({ payload, path: '/de/parent/' })

    expect(result?.doc.id).toBe(page.id)
    expect(result?.doc.path).toBe('/de/parent')
  })

  test('rejects a path that does not start with a slash', async () => {
    await expect(findPageByPath({ payload, path: 'de/parent' })).rejects.toThrow()
  })

  test('rejects a call without a payload instance or request', async () => {
    await expect(findPageByPath({ path: '/de/parent' })).rejects.toThrow()
  })
})

describe('findPageByPath query options', () => {
  test('merges the path into a provided select so the result stays verifiable', async () => {
    await createPage({ title: 'Parent', slug: 'parent' })

    const result = await findPageByPath({
      payload,
      path: '/de/parent',
      select: { title: true },
    })

    expect(result?.doc.title).toBe('Parent')
    expect(result?.doc.path).toBe('/de/parent')
    expect(result?.doc.content).toBeUndefined()
  })

  test('applies an additional where filter', async () => {
    const page = await createPage({ title: 'Parent', slug: 'parent' })

    // restricted to the pages collection since `title` is not queryable on all page collections
    const scoped = await findPageByPath({
      payload,
      path: '/de/parent',
      collections: ['pages'],
      where: { title: { equals: 'Parent' } },
    })
    const excluded = await findPageByPath({
      payload,
      path: '/de/parent',
      collections: ['pages'],
      where: { title: { equals: 'Other' } },
    })

    expect(scoped?.doc.id).toBe(page.id)
    expect(excluded).toBeNull()
  })

  test('only searches the given collections', async () => {
    const parent = await createPage({ title: 'Autoren', slug: 'autoren' })
    await payload.create({
      collection: 'authors',
      locale: 'de',
      data: {
        name: 'Max Mustermann',
        content: 'Bio',
        slug: 'max-mustermann',
        parent: parent.id,
        ...virtualFields,
      },
    })

    const found = await findPageByPath({
      payload,
      path: '/de/autoren/max-mustermann',
      collections: ['authors'],
    })
    const notFound = await findPageByPath({
      payload,
      path: '/de/autoren/max-mustermann',
      collections: ['pages'],
    })

    expect(found?.collection).toBe('authors')
    expect(notFound).toBeNull()
  })

  test('rejects a collections option that contains a non-page collection', async () => {
    await expect(
      findPageByPath({ payload, path: '/de/parent', collections: ['users'] }),
    ).rejects.toThrow()
  })

  test('rejects an empty collections option', async () => {
    await expect(findPageByPath({ payload, path: '/de/parent', collections: [] })).rejects.toThrow()
  })
})

describe('Path cache', () => {
  test('caches a published resolution in the KV store and serves repeated lookups', async () => {
    const page = await createPage({ title: 'Parent', slug: 'parent' })

    const first = await findPageByPath({ payload, path: '/de/parent' })
    expect(first?.doc.id).toBe(page.id)
    expect(await pathCacheKeys()).toHaveLength(1)

    // repeated lookup (now served via the cached id) returns the same page
    const second = await findPageByPath({ payload, path: '/de/parent' })
    expect(second?.doc.id).toBe(page.id)
    expect(second?.doc.path).toBe('/de/parent')
  })

  test('does not return a page under its old path after it was renamed', async () => {
    const page = await createPage({ title: 'Page', slug: 'old-slug' })
    await findPageByPath({ payload, path: '/de/old-slug' })

    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'de',
      data: { slug: 'new-slug' },
    })

    expect(await findPageByPath({ payload, path: '/de/old-slug' })).toBeNull()
    expect((await findPageByPath({ payload, path: '/de/new-slug' }))?.doc.id).toBe(page.id)
  })

  test('does not return a page under its old path after it was moved to another parent', async () => {
    const parentA = await createPage({ title: 'A', slug: 'a' })
    const parentB = await createPage({ title: 'B', slug: 'b' })
    const child = await createPage({ title: 'Child', slug: 'child', parent: parentA.id })
    await findPageByPath({ payload, path: '/de/a/child' })

    await payload.update({
      collection: 'pages',
      id: child.id,
      locale: 'de',
      data: { parent: parentB.id },
    })

    expect(await findPageByPath({ payload, path: '/de/a/child' })).toBeNull()
    expect((await findPageByPath({ payload, path: '/de/b/child' }))?.doc.id).toBe(child.id)
  })

  test('a stale cache entry never resolves to the wrong page', async () => {
    const pageA = await createPage({ title: 'Page A', slug: 'shared' })
    await findPageByPath({ payload, path: '/de/shared' })

    // free up the slug and let a different page take over the path
    await payload.update({
      collection: 'pages',
      id: pageA.id,
      locale: 'de',
      data: { slug: 'moved-away' },
    })
    const pageB = await createPage({ title: 'Page B', slug: 'shared' })

    const result = await findPageByPath({ payload, path: '/de/shared' })

    expect(result?.doc.id).toBe(pageB.id)
  })

  test('verifies and self-heals a cache entry that points to the wrong page', async () => {
    const pageA = await createPage({ title: 'Page A', slug: 'page-a' })
    const pageB = await createPage({ title: 'Page B', slug: 'page-b' })

    await findPageByPath({ payload, path: '/de/page-a' })
    const [cacheKey] = await pathCacheKeys()

    // tamper with the cache entry so it points to a different page
    await payload.kv.set(cacheKey, { collection: 'pages', id: pageB.id })

    // the mismatch between the cached page's path and the requested path is detected,
    // the lookup falls back to the scan and the entry is corrected
    const result = await findPageByPath({ payload, path: '/de/page-a' })
    expect(result?.doc.id).toBe(pageA.id)

    const entry = await payload.kv.get<{ id: unknown }>(cacheKey)
    expect(entry?.id).toBe(pageA.id)
  })

  test('returns null for a cached path after the page was deleted', async () => {
    const page = await createPage({ title: 'Page', slug: 'page' })
    await findPageByPath({ payload, path: '/de/page' })

    await payload.delete({ collection: 'pages', id: page.id })

    expect(await findPageByPath({ payload, path: '/de/page' })).toBeNull()
  })

  test('does not write to the cache when disabled per call', async () => {
    await createPage({ title: 'Parent', slug: 'parent' })

    const result = await findPageByPath({ payload, path: '/de/parent', cache: false })

    expect(result).not.toBeNull()
    expect(await pathCacheKeys()).toHaveLength(0)
  })

  test('clearPathCache removes all cached path entries', async () => {
    await createPage({ title: 'Parent', slug: 'parent' })
    await findPageByPath({ payload, path: '/de/parent' })
    expect(await pathCacheKeys()).toHaveLength(1)

    await clearPathCache(payload)

    expect(await pathCacheKeys()).toHaveLength(0)
  })
})

describe('Draft pages', () => {
  test('resolves a never-published draft page only with draft: true', async () => {
    const draftPage = await createPage({ title: 'Draft', slug: 'draft-page', draft: true })

    expect(await findPageByPath({ payload, path: '/de/draft-page' })).toBeNull()

    const draftResult = await findPageByPath({ payload, path: '/de/draft-page', draft: true })
    expect(draftResult?.doc.id).toBe(draftPage.id)
  })

  test('serves repeated draft lookups from the cache and reflects draft content changes', async () => {
    const page = await createPage({ title: 'Post', slug: 'post', draft: true })

    // Warm the draft cache (the motivating preview case: SSR on every draft change).
    const first = await findPageByPath({ payload, path: '/de/post', draft: true })
    expect(first?.doc.id).toBe(page.id)
    expect(await pathCacheKeys()).toHaveLength(1)

    // A body change leaves the path unchanged, so the cached entry stays valid...
    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'de',
      draft: true,
      data: { content: 'Updated body' },
    })

    // ...yet the re-fetched document reflects the new content and the entry is not churned.
    const second = await findPageByPath({ payload, path: '/de/post', draft: true })
    expect(second?.doc.content).toBe('Updated body')
    expect(await pathCacheKeys()).toHaveLength(1)
  })

  test('a draft lookup neither reads nor evicts the cached published entry for the same path', async () => {
    const page = await createPage({ title: 'Iso', slug: 'iso' })

    // Warm the published cache for /de/iso.
    expect((await findPageByPath({ payload, path: '/de/iso' }))?.doc.id).toBe(page.id)
    expect(await pathCacheKeys()).toHaveLength(1)

    // Move the draft to a different path, so /de/iso no longer resolves as a draft.
    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'de',
      draft: true,
      data: { slug: 'iso-draft' },
    })

    // The draft lookup for /de/iso must not be served (or evict) the published entry.
    expect(await findPageByPath({ payload, path: '/de/iso', draft: true })).toBeNull()
    expect(await pathCacheKeys()).toHaveLength(1)

    // The published lookup is still served correctly from its untouched entry.
    expect((await findPageByPath({ payload, path: '/de/iso' }))?.doc.id).toBe(page.id)
  })

  test('resolves the published version when a newer draft changed the slug', async () => {
    const page = await createPage({ title: 'Published', slug: 'published-slug' })
    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'de',
      draft: true,
      data: { slug: 'draft-slug' },
    })

    // the published path still resolves to the published version
    const published = await findPageByPath({ payload, path: '/de/published-slug' })
    expect(published?.doc.id).toBe(page.id)
    expect(published?.doc.slug).toBe('published-slug')

    // the draft path only resolves with draft: true
    expect(await findPageByPath({ payload, path: '/de/draft-slug' })).toBeNull()
    const draft = await findPageByPath({ payload, path: '/de/draft-slug', draft: true })
    expect(draft?.doc.id).toBe(page.id)
    expect(draft?.doc.slug).toBe('draft-slug')
  })
})

/**
 * Helper function to delete all documents from a collection.
 */
const deleteCollection = async (collection: CollectionSlug) => {
  // use db.deleteMany instead of payload.delete to avoid running hooks
  await payload.db.deleteMany({
    collection: collection,
    where: {},
  })

  // this will fail for collections which have no versions enabled, therefore wrapped in a try catch
  try {
    await payload.db.deleteVersions({
      collection: collection,
      where: {},
    })
  } catch {}
}

/**
 * Deletion order for collections to respect foreign key constraints.
 * Collections are deleted in this order: children before parents.
 */
const COLLECTION_DELETION_ORDER: CollectionSlug[] = [
  'country-travel-tips',
  'blogposts',
  'authors',
  'countries',
  'pages',
  'blogpost-categories',
  'redirects',
]

const deleteAllCollections = async (
  config: Promise<SanitizedConfig>,
  except: CollectionSlug[] = [],
) => {
  const collections = (await config).collections?.filter((c) => !except.includes(c.slug)) ?? []
  const collectionSlugs = new Set(collections.map((c) => c.slug))

  for (const slug of COLLECTION_DELETION_ORDER) {
    if (collectionSlugs.has(slug)) {
      await deleteCollection(slug)
      collectionSlugs.delete(slug)
    }
  }

  for (const slug of Array.from(collectionSlugs)) {
    await deleteCollection(slug)
  }
}
