import payload, { createLocalReq } from 'payload'
import { afterAll, beforeAll, beforeEach, describe, expect, test } from 'vitest'
import {
  findPageByPath,
  listPagePaths,
  pathChanges,
  SKIP_PARENT_GUARD_CONTEXT_KEY,
} from '@jhb.software/payload-pages-plugin'
import config from './src/payload.config'
import type { Config } from 'payload/generated-types'
import { deleteCollection } from './src/test/deleteCollections'
import { instrumentDbOps, type DbOpsInstrumentation } from './src/test/dbOps'
import {
  clearPathChangeRecords,
  recordedPathChangeErrors,
  recordedPathChanges,
} from './src/test/pathChangesCapture'

type DefaultIDType = Config['db']['defaultIDType']

/**
 * Empty virtual fields that are generated by the plugin.
 * Spread this into data objects when creating documents to satisfy TypeScript.
 */
const virtualFields = {
  breadcrumbs: [],
  meta: { alternatePaths: [] },
  path: '',
}

let dbOps: DbOpsInstrumentation

beforeAll(async () => {
  await payload.init({ config })
  dbOps = instrumentDbOps(payload.db)
})

afterAll(async () => {
  if (payload.db && typeof payload.db.destroy === 'function') {
    await payload.db.destroy()
  }
})

/** Deletes every page collection's documents, children before parents. */
const wipePageCollections = async () => {
  for (const slug of [
    'country-travel-tips',
    'blogposts',
    'authors',
    'announcements',
    'topics',
    'countries',
    'pages',
  ] as const) {
    await deleteCollection(slug)
  }
}

const createPage = async (data: {
  title: string
  slug: string
  parent?: DefaultIDType
  isRootPage?: boolean
  _status?: 'draft' | 'published'
}) =>
  await payload.create({
    collection: 'pages',
    locale: 'de',
    data: { content: 'Content', _status: 'published', ...virtualFields, ...data },
  })

const createTopic = async (data: {
  title: string
  slug: string
  parent: { relationTo: 'pages' | 'topics'; value: DefaultIDType }
}) =>
  await payload.create({
    collection: 'topics',
    locale: 'de',
    data: { _status: 'published', breadcrumbs: [], path: '', ...data },
  })

describe('listPagePaths', () => {
  beforeEach(async () => {
    await wipePageCollections()
    clearPathChangeRecords()
  })

  test('returns every live path across all page collections without naming them', async () => {
    const about = await createPage({ title: 'About', slug: 'about' })
    const team = await createPage({ title: 'Team', slug: 'team', parent: about.id })
    const country = await payload.create({
      collection: 'countries',
      locale: 'de',
      data: {
        title: 'Germany',
        slug: 'germany',
        content: 'Content',
        parent: about.id,
        _status: 'published',
        ...virtualFields,
      },
    })
    // a draft page must not appear
    await createPage({ title: 'Secret', slug: 'secret', _status: 'draft' })

    const req = await createLocalReq({}, payload)
    const entries = await listPagePaths({ req })

    expect(new Set(entries.map((entry) => entry.path))).toEqual(
      new Set(['/de/about', '/de/about/team', '/de/about/germany']),
    )

    const teamEntry = entries.find((entry) => entry.path === '/de/about/team')!
    expect(teamEntry).toMatchObject({
      collection: 'pages',
      id: team.id,
      locale: 'de',
      title: 'Team',
    })
    expect(typeof teamEntry.updatedAt).toBe('string')

    const countryEntry = entries.find((entry) => entry.path === '/de/about/germany')!
    expect(countryEntry.collection).toBe('countries')
    expect(countryEntry.id).toBe(country.id)
  })

  test('excludes drafts by default and includes them under draft: true', async () => {
    await createPage({ title: 'Published', slug: 'published' })
    const draft = await createPage({
      title: 'Never Published',
      slug: 'never-published',
      _status: 'draft',
    })

    const req = await createLocalReq({}, payload)

    const publishedEntries = await listPagePaths({ req })
    expect(publishedEntries.map((entry) => entry.path)).toEqual(['/de/published'])

    const draftEntries = await listPagePaths({ draft: true, req })
    expect(new Set(draftEntries.map((entry) => entry.path))).toEqual(
      new Set(['/de/published', '/de/never-published']),
    )
    expect(draftEntries.find((entry) => entry.path === '/de/never-published')?.id).toBe(draft.id)
  })

  test('excludes trashed documents and restoring one brings it back', async () => {
    const page = await createPage({ title: 'Trashable', slug: 'trashable' })

    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'de',
      data: { deletedAt: new Date().toISOString() },
    })

    const req = await createLocalReq({}, payload)
    expect(await listPagePaths({ req })).toEqual([])

    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'de',
      trash: true,
      data: { deletedAt: null, _status: 'published' },
    })

    const entries = await listPagePaths({ req: await createLocalReq({}, payload) })
    expect(entries.map((entry) => entry.path)).toEqual(['/de/trashable'])
  })

  test('a caller where composes with the plugin conditions rather than replacing them', async () => {
    await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Secret',
        slug: 'where-draft',
        content: 'Content',
        _status: 'draft',
        ...virtualFields,
        meta: { title: 'Secret Meta', alternatePaths: [] },
      },
    })

    const req = await createLocalReq({}, payload)
    // this where matches the draft, but the published-only condition must still apply
    const entries = await listPagePaths({
      collections: ['pages'],
      req,
      where: { 'meta.title': { equals: 'Secret Meta' } },
    })
    expect(entries).toEqual([])
  })

  test('title comes from each collection`s configured breadcrumbs.labelField', async () => {
    const parent = await createPage({ title: 'Blog', slug: 'blog' })
    const author = await payload.create({
      collection: 'authors',
      locale: 'de',
      data: {
        name: 'Author',
        slug: 'author',
        content: 'Content',
        parent: parent.id,
        ...virtualFields,
      },
    })
    // blogposts configure `breadcrumbs.labelField: 'shortTitle'` and have no drafts
    await payload.create({
      collection: 'blogposts',
      locale: 'de',
      data: {
        title: 'A Very Long Blogpost Title',
        shortTitle: 'Short',
        slug: 'post',
        content: 'Content',
        author: author.id,
        parent: parent.id,
        ...virtualFields,
      },
    })

    const req = await createLocalReq({}, payload)
    const entries = await listPagePaths({ req })

    expect(entries.find((entry) => entry.collection === 'blogposts')?.title).toBe('Short')
    expect(entries.find((entry) => entry.collection === 'pages')?.title).toBe('Blog')
  })

  test('returns one entry per locale and none for a locale whose slug is unset', async () => {
    const page = await createPage({ title: 'Localized', slug: 'localized-de' })
    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'en',
      data: {
        title: 'Localized EN',
        content: 'Content',
        slug: 'localized-en',
        _status: 'published',
      },
    })
    // this page only has a German slug
    await createPage({ title: 'German only', slug: 'german-only' })

    const req = await createLocalReq({}, payload)
    const entries = await listPagePaths({ req })

    expect(new Set(entries.map((entry) => `${entry.locale}:${entry.path}`))).toEqual(
      new Set(['de:/de/localized-de', 'en:/en/localized-en', 'de:/de/german-only']),
    )
    // the title is picked per entry from the locale the path belongs to
    expect(entries.find((entry) => entry.path === '/de/localized-de')?.title).toBe('Localized')
    expect(entries.find((entry) => entry.path === '/en/localized-en')?.title).toBe('Localized EN')

    const enEntries = await listPagePaths({ locale: 'en', req })
    expect(enEntries.map((entry) => entry.path)).toEqual(['/en/localized-en'])
  })

  test('the collections argument narrows enumeration to the given collections', async () => {
    const page = await createPage({ title: 'Page', slug: 'only-pages' })
    await payload.create({
      collection: 'countries',
      locale: 'de',
      data: {
        title: 'France',
        slug: 'france',
        content: 'Content',
        parent: page.id,
        _status: 'published',
        ...virtualFields,
      },
    })

    const req = await createLocalReq({}, payload)
    const entries = await listPagePaths({ collections: ['pages'], req })
    expect(entries.map((entry) => entry.path)).toEqual(['/de/only-pages'])
  })

  test('rejects a collections argument naming a non-page collection', async () => {
    const req = await createLocalReq({}, payload)
    await expect(listPagePaths({ collections: ['users'], req })).rejects.toThrow(
      'The collection "users" is not a page collection.',
    )
  })

  test('includes the root page under its bare locale prefix', async () => {
    const root = await createPage({ title: 'Root', slug: '', isRootPage: true })
    await createPage({ title: 'Under Root', slug: 'under-root', parent: root.id })

    const req = await createLocalReq({}, payload)
    const entries = await listPagePaths({ req })

    expect(new Set(entries.map((entry) => entry.path))).toEqual(new Set(['/de', '/de/under-root']))
    expect(entries.find((entry) => entry.path === '/de')).toMatchObject({
      collection: 'pages',
      id: root.id,
      locale: 'de',
      title: 'Root',
    })
  })
})

describe('pathChanges', () => {
  beforeEach(async () => {
    await wipePageCollections()
    clearPathChangeRecords()
  })

  test('renaming a slug in a draft and then publishing returns the previously published path as previousPath', async () => {
    const page = await createPage({ title: 'Rename Me', slug: 'old-name' })

    // rename in a draft: the live URL stays /de/old-name
    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'de',
      draft: true,
      data: { slug: 'new-name', _status: 'draft' },
    })

    clearPathChangeRecords()
    // publish the draft: the live URL moves to /de/new-name
    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'de',
      data: { _status: 'published' },
    })

    expect(recordedPathChangeErrors()).toEqual([])
    expect(recordedPathChanges()).toEqual([
      expect.objectContaining({
        collection: 'pages',
        id: page.id,
        locale: 'de',
        previousPath: '/de/old-name',
        path: '/de/new-name',
      }),
    ])
  })

  test('a draft save of a published page returns an empty array and issues no capture read', async () => {
    const page = await createPage({ title: 'Draft Save', slug: 'draft-save' })

    clearPathChangeRecords()
    dbOps.start()
    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'de',
      draft: true,
      data: { title: 'Draft Save Edited', _status: 'draft' },
    })
    const ops = dbOps.stop()

    expect(recordedPathChangeErrors()).toEqual([])
    expect(recordedPathChanges()).toEqual([])
    // the capture read is the only query which selects the main row's slug on this parentless page
    expect(
      ops.filter(
        (op) =>
          op.collection === 'pages' && op.method === 'find' && op.selectFields?.includes('slug'),
      ),
    ).toEqual([])
  })

  test('an autosave tick returns an empty array', async () => {
    const countryParent = await createPage({ title: 'Countries', slug: 'countries' })
    const country = await payload.create({
      collection: 'countries',
      locale: 'de',
      data: {
        title: 'Autosave Country',
        slug: 'autosave-country',
        content: 'Content',
        parent: countryParent.id,
        _status: 'published',
        ...virtualFields,
      },
    })
    const tip = await payload.create({
      collection: 'country-travel-tips',
      locale: 'de',
      data: {
        title: 'Tips',
        slug: 'reisetipps',
        content: 'Content',
        country: country.id,
        _status: 'published',
        ...virtualFields,
      },
    })

    clearPathChangeRecords()
    await payload.update({
      collection: 'country-travel-tips',
      id: tip.id,
      locale: 'de',
      draft: true,
      autosave: true,
      data: { title: 'Tips (autosaved)', _status: 'draft' },
    })

    expect(recordedPathChangeErrors()).toEqual([])
    expect(recordedPathChanges()).toEqual([])
  })

  test('renaming a parent slug returns one entry per affected document across every depth and collection', async () => {
    const a = await createPage({ title: 'A', slug: 'a' })
    const b = await createPage({ title: 'B', slug: 'b', parent: a.id })
    const c = await createPage({ title: 'C', slug: 'c', parent: b.id })
    const t = await createTopic({
      title: 'T',
      slug: 't',
      parent: { relationTo: 'pages', value: b.id },
    })
    const t2 = await createTopic({
      title: 'T2',
      slug: 't2',
      parent: { relationTo: 'topics', value: t.id },
    })

    clearPathChangeRecords()
    await payload.update({
      collection: 'pages',
      id: a.id,
      locale: 'de',
      data: { slug: 'a2', _status: 'published' },
    })

    expect(recordedPathChangeErrors()).toEqual([])
    const changes = recordedPathChanges()
    const byId = new Map(changes.map((change) => [`${change.collection}:${change.id}`, change]))

    expect(changes).toHaveLength(5)
    expect(byId.get(`pages:${a.id}`)).toMatchObject({ previousPath: '/de/a', path: '/de/a2' })
    expect(byId.get(`pages:${b.id}`)).toMatchObject({ previousPath: '/de/a/b', path: '/de/a2/b' })
    expect(byId.get(`pages:${c.id}`)).toMatchObject({
      previousPath: '/de/a/b/c',
      path: '/de/a2/b/c',
    })
    expect(byId.get(`topics:${t.id}`)).toMatchObject({
      previousPath: '/de/a/b/t',
      path: '/de/a2/b/t',
    })
    expect(byId.get(`topics:${t2.id}`)).toMatchObject({
      previousPath: '/de/a/b/t/t2',
      path: '/de/a2/b/t/t2',
    })
  })

  test('a content-only edit returns an empty array and issues no subtree query', async () => {
    const parent = await createPage({ title: 'Content Parent', slug: 'content-parent' })
    await createPage({ title: 'Content Child', slug: 'content-child', parent: parent.id })

    clearPathChangeRecords()
    dbOps.start()
    await payload.update({
      collection: 'pages',
      id: parent.id,
      locale: 'de',
      data: { content: 'Edited content', _status: 'published' },
    })
    const ops = dbOps.stop()

    expect(recordedPathChangeErrors()).toEqual([])
    expect(recordedPathChanges()).toEqual([])
    // a subtree query filters on the parent field
    expect(
      ops.filter(
        (op) =>
          op.method === 'find' &&
          op.whereFields?.some((field) => field === 'parent' || field.startsWith('parent.')),
      ),
    ).toEqual([])
  })

  test('a create returns one entry with previousPath null, a draft create returns none', async () => {
    await createPage({ title: 'Fresh', slug: 'fresh' })
    expect(recordedPathChangeErrors()).toEqual([])
    expect(recordedPathChanges()).toEqual([
      expect.objectContaining({
        collection: 'pages',
        locale: 'de',
        previousPath: null,
        path: '/de/fresh',
      }),
    ])

    clearPathChangeRecords()
    await createPage({ title: 'Fresh Draft', slug: 'fresh-draft', _status: 'draft' })
    expect(recordedPathChangeErrors()).toEqual([])
    expect(recordedPathChanges()).toEqual([])
  })

  test('a hard delete returns one entry carrying the path the document had', async () => {
    const page = await createPage({ title: 'Doomed', slug: 'doomed' })

    clearPathChangeRecords()
    await payload.delete({ collection: 'pages', id: page.id })

    expect(recordedPathChangeErrors()).toEqual([])
    expect(recordedPathChanges()).toEqual([
      expect.objectContaining({
        collection: 'pages',
        id: page.id,
        locale: 'de',
        previousPath: '/de/doomed',
        path: null,
      }),
    ])
  })

  test('a bulk delete returns one entry per deleted document', async () => {
    const one = await createPage({ title: 'Bulk One', slug: 'bulk-one' })
    const two = await createPage({ title: 'Bulk Two', slug: 'bulk-two' })

    clearPathChangeRecords()
    await payload.delete({
      collection: 'pages',
      where: { slug: { in: ['bulk-one', 'bulk-two'] } },
      locale: 'de',
    })

    expect(recordedPathChangeErrors()).toEqual([])
    const changes = recordedPathChanges()
    const byId = new Map(changes.map((change) => [change.id, change]))

    expect(changes).toHaveLength(2)
    expect(byId.get(one.id)).toMatchObject({
      collection: 'pages',
      previousPath: '/de/bulk-one',
      path: null,
    })
    expect(byId.get(two.id)).toMatchObject({
      collection: 'pages',
      previousPath: '/de/bulk-two',
      path: null,
    })
  })

  test('unpublishing returns path null and republishing returns previousPath null', async () => {
    const page = await createPage({ title: 'Pub', slug: 'pub-cycle' })

    clearPathChangeRecords()
    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'de',
      data: { _status: 'draft' },
    })
    expect(recordedPathChangeErrors()).toEqual([])
    expect(recordedPathChanges()).toEqual([
      expect.objectContaining({
        collection: 'pages',
        id: page.id,
        locale: 'de',
        previousPath: '/de/pub-cycle',
        path: null,
      }),
    ])

    clearPathChangeRecords()
    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'de',
      data: { _status: 'published' },
    })
    expect(recordedPathChangeErrors()).toEqual([])
    expect(recordedPathChanges()).toEqual([
      expect.objectContaining({
        collection: 'pages',
        id: page.id,
        locale: 'de',
        previousPath: null,
        path: '/de/pub-cycle',
      }),
    ])
  })

  test('trashing returns path null and restoring returns previousPath null, both through afterChange', async () => {
    const page = await createPage({ title: 'Trash Cycle', slug: 'trash-cycle' })

    clearPathChangeRecords()
    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'de',
      data: { deletedAt: new Date().toISOString() },
    })
    expect(recordedPathChangeErrors()).toEqual([])
    expect(recordedPathChanges()).toEqual([
      expect.objectContaining({
        collection: 'pages',
        id: page.id,
        locale: 'de',
        previousPath: '/de/trash-cycle',
        path: null,
      }),
    ])

    clearPathChangeRecords()
    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'de',
      trash: true,
      data: { deletedAt: null, _status: 'published' },
    })
    expect(recordedPathChangeErrors()).toEqual([])
    expect(recordedPathChanges()).toEqual([
      expect.objectContaining({
        collection: 'pages',
        id: page.id,
        locale: 'de',
        previousPath: null,
        path: '/de/trash-cycle',
      }),
    ])
  })

  test('moving a document to a new parent returns entries for the document and its descendants', async () => {
    const oldParent = await createPage({ title: 'Old Parent', slug: 'old-parent' })
    const newParent = await createPage({ title: 'New Parent', slug: 'new-parent' })
    const child = await createPage({ title: 'Child', slug: 'child', parent: oldParent.id })
    const grandchild = await createPage({
      title: 'Grandchild',
      slug: 'grandchild',
      parent: child.id,
    })

    clearPathChangeRecords()
    await payload.update({
      collection: 'pages',
      id: child.id,
      locale: 'de',
      data: { parent: newParent.id, _status: 'published' },
    })

    expect(recordedPathChangeErrors()).toEqual([])
    const changes = recordedPathChanges()
    const byId = new Map(changes.map((change) => [change.id, change]))

    expect(changes).toHaveLength(2)
    expect(byId.get(child.id)).toMatchObject({
      previousPath: '/de/old-parent/child',
      path: '/de/new-parent/child',
    })
    expect(byId.get(grandchild.id)).toMatchObject({
      previousPath: '/de/old-parent/child/grandchild',
      path: '/de/new-parent/child/grandchild',
    })
  })

  test('renaming only one locale`s slug returns an entry for that locale only', async () => {
    const page = await createPage({ title: 'Locales', slug: 'locales-de' })
    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'en',
      data: { title: 'Locales EN', content: 'Content', slug: 'locales-en', _status: 'published' },
    })

    clearPathChangeRecords()
    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'en',
      data: { slug: 'locales-en-renamed', _status: 'published' },
    })

    expect(recordedPathChangeErrors()).toEqual([])
    expect(recordedPathChanges()).toEqual([
      expect.objectContaining({
        locale: 'en',
        previousPath: '/en/locales-en',
        path: '/en/locales-en-renamed',
      }),
    ])
  })

  test('hard-deleting a parent with the guard skipped returns previousPath → null entries for its descendants', async () => {
    const parent = await createPage({ title: 'Doomed Parent', slug: 'doomed-parent' })
    const child = await createPage({
      title: 'Doomed Child',
      slug: 'doomed-child',
      parent: parent.id,
    })
    const grandchild = await createPage({
      title: 'Doomed Grandchild',
      slug: 'doomed-grandchild',
      parent: child.id,
    })

    clearPathChangeRecords()
    await payload.delete({
      collection: 'pages',
      id: parent.id,
      context: { [SKIP_PARENT_GUARD_CONTEXT_KEY]: true },
    })

    expect(recordedPathChangeErrors()).toEqual([])
    const changes = recordedPathChanges()
    const byId = new Map(changes.map((change) => [change.id, change]))

    expect(changes).toHaveLength(3)
    expect(byId.get(parent.id)).toMatchObject({ previousPath: '/de/doomed-parent', path: null })
    expect(byId.get(child.id)).toMatchObject({
      previousPath: '/de/doomed-parent/doomed-child',
      path: null,
    })
    expect(byId.get(grandchild.id)).toMatchObject({
      previousPath: '/de/doomed-parent/doomed-child/doomed-grandchild',
      path: null,
    })
  })

  test('a document whose ancestor chain is broken reports no live path, matching findPageByPath', async () => {
    const grandparent = await createPage({ title: 'Gone Grandparent', slug: 'gone-grandparent' })
    const parent = await createPage({
      title: 'Gone Parent',
      slug: 'gone-parent',
      parent: grandparent.id,
    })
    const child = await createPage({ title: 'Orphan', slug: 'orphan', parent: parent.id })

    // break the chain one level up so the child's own parent still exists (and its
    // relationship field stays valid): the grandparent's deletion already reported
    // the descendants' paths as gone
    await payload.delete({
      collection: 'pages',
      id: grandparent.id,
      context: { [SKIP_PARENT_GUARD_CONTEXT_KEY]: true },
    })

    clearPathChangeRecords()
    await payload.update({
      collection: 'pages',
      id: child.id,
      locale: 'de',
      data: { content: 'Edited', _status: 'published' },
    })

    // the orphan's path resolves neither before nor after the write
    expect(recordedPathChangeErrors()).toEqual([])
    expect(recordedPathChanges()).toEqual([])
    expect(
      await findPageByPath({
        cache: false,
        path: '/de/gone-grandparent/gone-parent/orphan',
        req: await createLocalReq({}, payload),
      }),
    ).toBeNull()
  })

  test('a narrow select on the update that renames a slug still produces complete entries', async () => {
    const parent = await createPage({ title: 'Select Parent', slug: 'select-parent' })
    const child = await createPage({
      title: 'Select Child',
      slug: 'select-child',
      parent: parent.id,
    })

    clearPathChangeRecords()
    await payload.update({
      collection: 'pages',
      id: parent.id,
      locale: 'de',
      select: { title: true },
      data: { slug: 'select-parent-renamed', _status: 'published' },
    })

    expect(recordedPathChangeErrors()).toEqual([])
    const changes = recordedPathChanges()
    const byId = new Map(changes.map((change) => [change.id, change]))

    expect(changes).toHaveLength(2)
    expect(byId.get(parent.id)).toMatchObject({
      previousPath: '/de/select-parent',
      path: '/de/select-parent-renamed',
    })
    expect(byId.get(child.id)).toMatchObject({
      previousPath: '/de/select-parent/select-child',
      path: '/de/select-parent-renamed/select-child',
    })
  })

  test('a write that renames the slug and unpublishes at once reports the descendants` moved paths', async () => {
    const parent = await createPage({ title: 'Combo Parent', slug: 'combo-parent' })
    const child = await createPage({ title: 'Combo Child', slug: 'combo-child', parent: parent.id })

    clearPathChangeRecords()
    await payload.update({
      collection: 'pages',
      id: parent.id,
      locale: 'de',
      data: { slug: 'combo-parent-renamed', _status: 'draft' },
    })

    // the still-published child now resolves under the renamed segment only
    const req = await createLocalReq({}, payload)
    expect(
      (await findPageByPath({ cache: false, path: '/de/combo-parent-renamed/combo-child', req }))
        ?.doc.id,
    ).toBe(child.id)
    expect(
      await findPageByPath({ cache: false, path: '/de/combo-parent/combo-child', req }),
    ).toBeNull()

    expect(recordedPathChangeErrors()).toEqual([])
    const changes = recordedPathChanges()
    const byId = new Map(changes.map((change) => [change.id, change]))

    expect(changes).toHaveLength(2)
    expect(byId.get(parent.id)).toMatchObject({ previousPath: '/de/combo-parent', path: null })
    expect(byId.get(child.id)).toMatchObject({
      previousPath: '/de/combo-parent/combo-child',
      path: '/de/combo-parent-renamed/combo-child',
    })
  })

  test('restoring a previous version reports the move back to the restored slug', async () => {
    const page = await createPage({ title: 'Versioned', slug: 'version-one' })
    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'de',
      data: { slug: 'version-two', _status: 'published' },
    })

    const { docs: versions } = await payload.findVersions({
      collection: 'pages',
      locale: 'de',
      sort: '-createdAt',
      where: { parent: { equals: page.id } },
    })
    const versionOne = versions.find((version) => version.version.slug === 'version-one')!

    clearPathChangeRecords()
    await payload.restoreVersion({ collection: 'pages', id: versionOne.id })

    expect(recordedPathChangeErrors()).toEqual([])
    expect(recordedPathChanges()).toEqual([
      expect.objectContaining({
        collection: 'pages',
        id: page.id,
        locale: 'de',
        previousPath: '/de/version-two',
        path: '/de/version-one',
      }),
    ])
  })

  test('a draft save whose data omits _status reports nothing', async () => {
    const page = await createPage({ title: 'Implicit Draft', slug: 'implicit-draft' })

    clearPathChangeRecords()
    await payload.update({
      collection: 'pages',
      id: page.id,
      locale: 'de',
      draft: true,
      data: { title: 'Implicit Draft Edited' },
    })

    expect(recordedPathChangeErrors()).toEqual([])
    expect(recordedPathChanges()).toEqual([])
  })

  test('publishing and unpublishing the root page reports its bare locale-prefix path', async () => {
    const root = await createPage({ title: 'Root', slug: '', isRootPage: true })
    expect(recordedPathChangeErrors()).toEqual([])
    expect(recordedPathChanges()).toEqual([
      expect.objectContaining({
        collection: 'pages',
        id: root.id,
        locale: 'de',
        previousPath: null,
        path: '/de',
      }),
    ])

    clearPathChangeRecords()
    await payload.update({
      collection: 'pages',
      id: root.id,
      locale: 'de',
      data: { _status: 'draft' },
    })
    expect(recordedPathChangeErrors()).toEqual([])
    expect(recordedPathChanges()).toEqual([
      expect.objectContaining({
        collection: 'pages',
        id: root.id,
        locale: 'de',
        previousPath: '/de',
        path: null,
      }),
    ])
  })

  test('re-parenting a document across its polymorphic parent`s collections reports the moved paths', async () => {
    const page = await createPage({ title: 'Poly Root', slug: 'poly-root' })
    const topicParent = await createTopic({
      title: 'Topic A',
      slug: 'topic-a',
      parent: { relationTo: 'pages', value: page.id },
    })
    const mover = await createTopic({
      title: 'Mover',
      slug: 'mover',
      parent: { relationTo: 'pages', value: page.id },
    })
    const leaf = await createTopic({
      title: 'Leaf',
      slug: 'leaf',
      parent: { relationTo: 'topics', value: mover.id },
    })

    clearPathChangeRecords()
    await payload.update({
      collection: 'topics',
      id: mover.id,
      locale: 'de',
      data: { parent: { relationTo: 'topics', value: topicParent.id }, _status: 'published' },
    })

    expect(recordedPathChangeErrors()).toEqual([])
    const changes = recordedPathChanges()
    const byId = new Map(changes.map((change) => [change.id, change]))

    expect(changes).toHaveLength(2)
    expect(byId.get(mover.id)).toMatchObject({
      previousPath: '/de/poly-root/mover',
      path: '/de/poly-root/topic-a/mover',
    })
    expect(byId.get(leaf.id)).toMatchObject({
      previousPath: '/de/poly-root/mover/leaf',
      path: '/de/poly-root/topic-a/mover/leaf',
    })
  })

  test('a bulk delete removing a parent together with its descendant reports the descendant from both hook invocations', async () => {
    // created (and therefore deleted) before the child, so the parent's descendant capture
    // still sees the child — the double report the API documents as harmless
    const parent = await createPage({ title: 'Dup Parent', slug: 'dup-parent' })
    const child = await createPage({ title: 'Dup Child', slug: 'dup-child', parent: parent.id })

    clearPathChangeRecords()
    await payload.delete({
      collection: 'pages',
      where: { slug: { in: ['dup-parent', 'dup-child'] } },
      locale: 'de',
      context: { [SKIP_PARENT_GUARD_CONTEXT_KEY]: true },
    })

    expect(recordedPathChangeErrors()).toEqual([])
    const changes = recordedPathChanges()

    expect(changes.filter((change) => change.id === parent.id)).toEqual([
      expect.objectContaining({ previousPath: '/de/dup-parent', path: null }),
    ])
    expect(changes.filter((change) => change.id === child.id)).toEqual([
      expect.objectContaining({ previousPath: '/de/dup-parent/dup-child', path: null }),
      expect.objectContaining({ previousPath: '/de/dup-parent/dup-child', path: null }),
    ])
  })

  test('a failed pre-write capture surfaces as a rejection instead of silently shortening the result', async () => {
    const page = await createPage({ title: 'Capture Fail', slug: 'capture-fail' })

    // fail exactly the capture read: the find by the page's own id selecting its slug
    const originalFind = payload.db.find
    payload.db.find = (async (args: any) => {
      if (
        args?.collection === 'pages' &&
        args?.select?.slug === true &&
        args?.where?.id?.equals === page.id
      ) {
        throw new Error('injected capture failure')
      }
      return originalFind.call(payload.db, args)
    }) as typeof payload.db.find

    clearPathChangeRecords()
    try {
      await payload.update({
        collection: 'pages',
        id: page.id,
        locale: 'de',
        data: { slug: 'capture-fail-renamed', _status: 'published' },
      })
    } finally {
      payload.db.find = originalFind
    }

    expect(recordedPathChanges()).toEqual([])
    const errors = recordedPathChangeErrors()
    expect(errors).toHaveLength(1)
    expect((errors[0] as Error).message).toBe('injected capture failure')
  })

  test('rejects when called without a pre-write capture instead of returning a short list', async () => {
    const page = await createPage({ title: 'Misuse', slug: 'misuse' })
    const req = await createLocalReq({}, payload)

    await expect(
      pathChanges({
        collection: payload.collections.pages.config,
        doc: { id: page.id, _status: 'published' },
        previousDoc: {},
        operation: 'update',
        req,
      } as any),
    ).rejects.toThrow(/no captured pre-write state/)
  })
})

describe('enumeration and change detection agree', () => {
  beforeEach(async () => {
    await wipePageCollections()
    clearPathChangeRecords()
  })

  test('listPagePaths matches findPageByPath, and applying pathChanges results reproduces a fresh enumeration', async () => {
    const parent = await createPage({ title: 'Agree Parent', slug: 'agree-parent' })
    const child = await createPage({ title: 'Agree Child', slug: 'agree-child', parent: parent.id })
    await createPage({ title: 'Agree Draft', slug: 'agree-draft', _status: 'draft' })
    const trashed = await createPage({ title: 'Agree Trashed', slug: 'agree-trashed' })
    await payload.update({
      collection: 'pages',
      id: trashed.id,
      locale: 'de',
      data: { deletedAt: new Date().toISOString() },
    })

    const entries = await listPagePaths({ req: await createLocalReq({}, payload) })

    // every enumerated path resolves to the same document, and only those paths resolve
    for (const entry of entries) {
      const resolved = await findPageByPath({
        cache: false,
        path: entry.path,
        req: await createLocalReq({}, payload),
      })
      expect(resolved?.doc.id).toBe(entry.id)
    }
    for (const deadPath of ['/de/agree-draft', '/de/agree-trashed']) {
      expect(
        await findPageByPath({
          cache: false,
          path: deadPath,
          req: await createLocalReq({}, payload),
        }),
      ).toBeNull()
    }

    // apply every pathChanges result to the enumerated set: it must reproduce a fresh enumeration
    const paths = new Set(entries.map((entry) => entry.path))
    clearPathChangeRecords()

    await payload.update({
      collection: 'pages',
      id: parent.id,
      locale: 'de',
      data: { slug: 'agree-parent-renamed', _status: 'published' },
    })
    await payload.update({
      collection: 'pages',
      id: child.id,
      locale: 'de',
      data: { _status: 'draft' },
    })
    await payload.update({
      collection: 'pages',
      id: trashed.id,
      locale: 'de',
      trash: true,
      data: { deletedAt: null, _status: 'published' },
    })
    await createPage({ title: 'Agree New', slug: 'agree-new' })

    expect(recordedPathChangeErrors()).toEqual([])
    for (const change of recordedPathChanges()) {
      if (change.previousPath) paths.delete(change.previousPath)
      if (change.path) paths.add(change.path)
    }

    const fresh = await listPagePaths({ req: await createLocalReq({}, payload) })
    expect(paths).toEqual(new Set(fresh.map((entry) => entry.path)))
  })
})
