import payload, { CollectionSlug, SanitizedConfig, ValidationError } from 'payload'
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, test, vi } from 'vitest'
import config from './src/payload.config'
import type { Config } from 'payload/generated-types'
import {
  clearCapturedAfterChanges,
  getLastAfterChangeHookArgs,
} from './src/test/afterChangeCapture'

type DefaultIDType = Config['db']['defaultIDType']

/**
 * Empty virtual fields that are generated by the plugin.
 * Spread this into data objects when creating documents to satisfy TypeScript.
 */
const virtualFields = {
  breadcrumbs: [],
  meta: { alternatePaths: [] },
  path: '',
}

beforeAll(async () => {
  await payload.init({
    config: config,
  })

  // clear all collections except users
  await deleteAllCollections(config, ['users'])
})

afterAll(async () => {
  await deleteAllCollections(config)

  if (payload.db && typeof payload.db.destroy === 'function') {
    await payload.db.destroy()
  } else {
    console.log('Could not destroy database')
  }
})

afterEach(() => {
  vi.restoreAllMocks()
})

describe('Path and breadcrumb virtual fields are returned correctly for find operation.', () => {
  describe('The root page document', () => {
    beforeEach(async () => await deleteCollection('pages'))

    test('has the correct virtual fields when only one locale is present', async () => {
      const locale = 'de'
      const rootPageData = {
        title: 'Root Page DE',
        slug: '',
        content: 'Root Page DE',
        isRootPage: true,
        ...virtualFields,
      }

      const rootPageId = (
        await payload.create({
          collection: 'pages',
          locale,
          data: rootPageData,
        })
      ).id

      const rootPage = await payload.findByID({
        collection: 'pages',
        id: rootPageId,
        locale: locale,
      })

      const path = `/${locale}`

      expect(rootPage.slug).toBe('') // Plugin convention: The slug of the root page is an empty string.
      expect(rootPage.path).toBe(path)
      expect(removeIdsFromArray(rootPage.breadcrumbs)).toEqual(
        removeIdsFromArray([
          {
            id: undefined,
            path,
            label: rootPageData.title,
            slug: rootPageData.slug,
          },
        ]),
      )
      expect(removeIdsFromArray(rootPage.meta?.alternatePaths)).toEqual(
        removeIdsFromArray([
          {
            id: undefined,
            hreflang: locale,
            path,
          },
        ]),
      )
    })

    test('has the correct virtual fields when all locales are present', async () => {
      const rootPageDataDe = {
        title: 'Root Page DE',
        slug: '',
        content: 'Root Page DE',
        isRootPage: true,
        ...virtualFields,
      }
      const rootPageDataEn = {
        title: 'Root Page EN',
        slug: '',
        content: 'Root Page EN',
        isRootPage: true,
        ...virtualFields,
      }

      const rootPageId = (
        await payload.create({
          collection: 'pages',
          locale: 'de',
          data: rootPageDataDe,
        })
      ).id

      await payload.update({
        collection: 'pages',
        id: rootPageId,
        locale: 'en',
        data: rootPageDataEn,
      })

      const rootPage = await payload.findByID({
        collection: 'pages',
        id: rootPageId,
        locale: 'all',
      })

      expect(rootPage.slug).toEqual({
        de: '',
        en: '',
      })
      expect(rootPage.path).toEqual({
        de: '/de',
        en: '/en',
      })

      // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
      expect(removeIdsFromArray(rootPage.breadcrumbs.de)).toEqual(
        removeIdsFromArray([
          {
            path: '/de',
            label: rootPageDataDe.title,
            slug: rootPageDataDe.slug,
          },
        ]),
      )
      // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
      expect(removeIdsFromArray(rootPage.breadcrumbs.en)).toEqual(
        removeIdsFromArray([
          {
            path: '/en',
            label: rootPageDataEn.title,
            slug: rootPageDataEn.slug,
          },
        ]),
      )
      expect(removeIdsFromArray(rootPage.meta.alternatePaths)).toEqual(
        removeIdsFromArray([
          {
            hreflang: 'de',
            path: '/de',
          },
          {
            hreflang: 'en',
            path: '/en',
          },
        ]),
      )
    })
  })

  describe('Nested document in same collection with all locales created.', () => {
    const rootPageDataDe = {
      title: 'Root Page DE',
      slug: 'root-page-de',
      content: 'Root Page DE',
    }
    const rootPageDataEn = {
      title: 'Root Page EN',
      slug: 'root-page-en',
      content: 'Root Page EN',
    }
    const nestedPageDataDe = {
      title: 'Nested Page DE',
      slug: 'nested-page-de',
      content: 'Nested Page DE',
    }
    const nestedPageDataEn = {
      title: 'Nested Page EN',
      slug: 'nested-page-en',
      content: 'Nested Page EN',
    }
    let rootPageId: DefaultIDType | undefined
    let nestedPageId: DefaultIDType | undefined

    beforeAll(async () => {
      await deleteCollection('pages')

      // ################# Seed the database for the tests of this group #################

      rootPageId = (
        await payload.create({
          collection: 'pages',
          locale: 'de',
          data: { ...rootPageDataDe, ...virtualFields },
        })
      ).id

      await payload.update({
        collection: 'pages',
        id: rootPageId,
        locale: 'en',
        data: { ...rootPageDataEn, ...virtualFields },
      })

      nestedPageId = (
        await payload.create({
          collection: 'pages',
          locale: 'de',
          data: { ...nestedPageDataDe, parent: rootPageId, ...virtualFields },
        })
      ).id

      await payload.update({
        collection: 'pages',
        id: nestedPageId,
        locale: 'en',
        data: { ...nestedPageDataEn, parent: rootPageId, ...virtualFields },
      })
    })

    describe('Breadcrumbs', () => {
      test('All locales requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'all',
        })

        expect(nestedPage).toBeDefined()

        // Breadcrumbs must be an object containing the breadcrumbs for all locales
        expect(typeof nestedPage.breadcrumbs).toBe('object')

        // Breadcrumbs must be correctly set
        expect(nestedPage.breadcrumbs).toStrictEqual({
          de: [
            {
              // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
              id: nestedPage.breadcrumbs.de[0]?.id,
              label: rootPageDataDe.title,
              slug: rootPageDataDe.slug,
              path: `/de/${rootPageDataDe.slug}`,
            },
            {
              // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
              id: nestedPage.breadcrumbs.de[1]?.id,
              label: nestedPageDataDe.title,
              slug: nestedPageDataDe.slug,
              path: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
            },
          ],
          en: [
            {
              // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
              id: nestedPage.breadcrumbs.en[0]?.id,
              label: rootPageDataEn.title,
              slug: rootPageDataEn.slug,
              path: `/en/${rootPageDataEn.slug}`,
            },
            {
              // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
              id: nestedPage.breadcrumbs.en[1]?.id,
              label: nestedPageDataEn.title,
              slug: nestedPageDataEn.slug,
              path: `/en/${rootPageDataEn.slug}/${nestedPageDataEn.slug}`,
            },
          ],
        })
      })

      test('One locale requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'de',
        })

        expect(nestedPage).toBeDefined()

        // Breadcrumbs must be an object containing the breadcrumbs for all locales
        expect(Array.isArray(nestedPage.breadcrumbs)).toBe(true)

        // Breadcrumbs must be correctly set
        expect(nestedPage.breadcrumbs).toStrictEqual([
          {
            id: nestedPage.breadcrumbs[0].id,
            label: rootPageDataDe.title,
            slug: rootPageDataDe.slug,
            path: `/de/${rootPageDataDe.slug}`,
          },
          {
            id: nestedPage.breadcrumbs[1].id,
            label: nestedPageDataDe.title,
            slug: nestedPageDataDe.slug,
            path: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
          },
        ])
      })
    })

    describe('Path', () => {
      test('All locales requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'all',
        })

        expect(nestedPage).toBeDefined()
        expect(nestedPage.path).toBeDefined()
        expect(typeof nestedPage.path).toBe('object')

        expect(nestedPage.path).toStrictEqual({
          de: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
          en: `/en/${rootPageDataEn.slug}/${nestedPageDataEn.slug}`,
        })
      })

      test('One locale requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'de',
        })

        expect(nestedPage).toBeDefined()
        expect(nestedPage.path).toBeDefined()
        expect(typeof nestedPage.path).toBe('string')

        expect(nestedPage.path).toStrictEqual(`/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`)
      })
    })

    describe('AlternatePaths', () => {
      test('All locales requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'all',
        })

        expect(nestedPage).toBeDefined()
        expect(nestedPage.meta.alternatePaths).toBeDefined()
        expect(Array.isArray(nestedPage.meta.alternatePaths)).toBe(true)

        expect(removeIdsFromArray(nestedPage.meta.alternatePaths)).toStrictEqual([
          {
            hreflang: 'de',
            path: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
          },
          {
            hreflang: 'en',
            path: `/en/${rootPageDataEn.slug}/${nestedPageDataEn.slug}`,
          },
        ])
      })

      test('One locale requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'de',
        })

        expect(nestedPage).toBeDefined()
        expect(nestedPage.meta.alternatePaths).toBeDefined()
        expect(Array.isArray(nestedPage.meta.alternatePaths)).toBe(true)

        expect(removeIdsFromArray(nestedPage.meta.alternatePaths)).toStrictEqual(
          removeIdsFromArray([
            {
              hreflang: 'de',
              path: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
            },
            {
              hreflang: 'en',
              path: `/en/${rootPageDataEn.slug}/${nestedPageDataEn.slug}`,
            },
          ]),
        )
      })
    })
  })

  describe('Nested document in same collection with one locale created.', () => {
    const rootPageDataDe = {
      title: 'Root Page DE',
      slug: 'root-page-de-one-locale',
      content: 'Root Page DE',
    }
    const nestedPageDataDe = {
      title: 'Nested Page DE',
      slug: 'nested-page-de-one-locale',
      content: 'Nested Page DE',
    }
    let rootPageId: DefaultIDType | undefined
    let nestedPageId: DefaultIDType | undefined

    beforeAll(async () => {
      await deleteCollection('pages')

      // ################# Seed the database for the tests of this group #################

      rootPageId = (
        await payload.create({
          collection: 'pages',
          locale: 'de',
          data: { ...rootPageDataDe, ...virtualFields },
        })
      ).id

      nestedPageId = (
        await payload.create({
          collection: 'pages',
          locale: 'de',
          data: { ...nestedPageDataDe, parent: rootPageId, ...virtualFields },
        })
      ).id
    })

    describe('Breadcrumbs', () => {
      test('All locales requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'all',
        })

        expect(nestedPage).toBeDefined()

        // Breadcrumbs must be an object containing the breadcrumbs for all locales
        expect(typeof nestedPage.breadcrumbs).toBe('object')

        // Breadcrumbs must be correctly set
        expect(nestedPage.breadcrumbs).toStrictEqual({
          de: [
            {
              // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
              id: nestedPage.breadcrumbs.de[0]?.id,
              label: rootPageDataDe.title,
              slug: rootPageDataDe.slug,
              path: `/de/${rootPageDataDe.slug}`,
            },
            {
              // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
              id: nestedPage.breadcrumbs.de[1]?.id,
              label: nestedPageDataDe.title,
              slug: nestedPageDataDe.slug,
              path: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
            },
          ],
          // TODO: After revising the implementation, change this to be undefined
          // Note: When the doc is not defined in en, the plugin should not return breadcrumbs for en!
          en: [
            {
              // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
              id: nestedPage.breadcrumbs.en[0]?.id,
              label: undefined,
              path: '/en',
              slug: undefined,
            },
            {
              // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
              id: nestedPage.breadcrumbs.en[1]?.id,
              label: undefined,
              path: '/en',
              slug: undefined,
            },
          ],
        })
      })

      test('One locale requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'de',
        })

        expect(nestedPage).toBeDefined()

        // Breadcrumbs must be an object containing the breadcrumbs for all locales
        expect(Array.isArray(nestedPage.breadcrumbs)).toBe(true)

        // Breadcrumbs must be correctly set
        expect(nestedPage.breadcrumbs).toStrictEqual([
          {
            id: nestedPage.breadcrumbs[0].id,
            label: rootPageDataDe.title,
            slug: rootPageDataDe.slug,
            path: `/de/${rootPageDataDe.slug}`,
          },
          {
            id: nestedPage.breadcrumbs[1].id,
            label: nestedPageDataDe.title,
            slug: nestedPageDataDe.slug,
            path: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
          },
        ])
      })
    })

    describe('Path', () => {
      test('All locales requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'all',
        })

        expect(nestedPage).toBeDefined()
        expect(nestedPage.path).toBeDefined()
        expect(typeof nestedPage.path).toBe('object')

        expect(nestedPage.path).toStrictEqual({
          de: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
        })
      })

      test('One locale requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'de',
        })

        expect(nestedPage).toBeDefined()
        expect(nestedPage.path).toBeDefined()
        expect(typeof nestedPage.path).toBe('string')

        expect(nestedPage.path).toStrictEqual(`/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`)
      })
    })

    describe('AlternatePaths', () => {
      test('All locales requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'all',
        })

        expect(nestedPage).toBeDefined()
        expect(nestedPage.meta.alternatePaths).toBeDefined()
        expect(Array.isArray(nestedPage.meta.alternatePaths)).toBe(true)

        expect(removeIdsFromArray(nestedPage.meta.alternatePaths)).toStrictEqual(
          removeIdsFromArray([
            {
              hreflang: 'de',
              path: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
            },
          ]),
        )
      })

      test('One locale requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'de',
        })

        expect(nestedPage).toBeDefined()
        expect(nestedPage.meta.alternatePaths).toBeDefined()
        expect(Array.isArray(nestedPage.meta.alternatePaths)).toBe(true)

        expect(removeIdsFromArray(nestedPage.meta.alternatePaths)).toStrictEqual(
          removeIdsFromArray([
            {
              hreflang: 'de',
              path: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
            },
          ]),
        )
      })
    })
  })

  test('Nested document across collections with one locale created.', async () => {
    const locale = 'de'
    const authorOverviewPageData = {
      title: 'Authors',
      slug: 'authors',
      content: 'Authors page',
    }
    const authorPageData = {
      name: 'Test Author',
      slug: 'test-author',
      content: 'Test Author',
    }

    const authorOverviewPageId = (
      await payload.create({
        collection: 'pages',
        locale,
        data: { ...authorOverviewPageData, ...virtualFields },
      })
    ).id

    const authorPageId = (
      await payload.create({
        collection: 'authors',
        locale,
        data: { ...authorPageData, parent: authorOverviewPageId, ...virtualFields },
      })
    ).id

    // Verify the author was created and linked correctly
    const author = await payload.findByID({
      collection: 'authors',
      depth: 0,
      id: authorPageId,
    })

    expect(author).toBeDefined()
    expect(author.parent).toBe(authorOverviewPageId)

    // Verify path is correctly set
    expect(author.path).toBe(`/${locale}/${authorOverviewPageData.slug}/${authorPageData.slug}`)

    // Verify breadcrumbs are correctly set
    expect(author.breadcrumbs).toBeDefined()
    expect(removeIdsFromArray(author.breadcrumbs)).toEqual([
      {
        label: authorOverviewPageData.title,
        path: `/${locale}/${authorOverviewPageData.slug}`,
        slug: authorOverviewPageData.slug,
      },
      {
        label: authorPageData.name,
        path: `/${locale}/${authorOverviewPageData.slug}/${authorPageData.slug}`,
        slug: authorPageData.slug,
      },
    ])

    // Verify alternatePaths are correctly set
    expect(author.meta.alternatePaths).toBeDefined()
    expect(removeIdsFromArray(author.meta.alternatePaths)).toEqual(
      removeIdsFromArray([
        {
          hreflang: locale,
          path: `/${locale}/${authorOverviewPageData.slug}/${authorPageData.slug}`,
        },
      ]),
    )
  })
})

describe('Path and breadcrumb virtual fields are set correctly for find operation with select.', () => {
  test('Only path and breadcrumbs are selected (not slug etc.)', async () => {
    const pageId = (
      await payload.create({
        collection: 'pages',
        locale: 'de',
        data: {
          title: 'Page DE',
          slug: 'page',
          content: 'Page DE',
          ...virtualFields,
        },
      })
    ).id

    const pageWithSelect = await payload.findByID({
      collection: 'pages',
      id: pageId,
      select: {
        path: true,
        breadcrumbs: true,
        meta: {
          alternatePaths: true,
        },
      },
    })

    const pageWithoutSelect = await payload.findByID({
      collection: 'pages',
      id: pageId,
    })

    // Breadcrumbs must be an array
    expect(Array.isArray(pageWithSelect.breadcrumbs)).toBe(true)

    // Breadcrumbs array should match homePage breadcrumbs
    expect(removeIdsFromArray(pageWithSelect.breadcrumbs)).toEqual(
      removeIdsFromArray(pageWithoutSelect.breadcrumbs),
    )

    // Path must be defined and non-empty
    expect(pageWithSelect.path).toBeDefined()

    // Path must be defined and non-empty
    expect(pageWithSelect.path).toEqual(pageWithoutSelect.path)

    // AlternatePaths must be defined and non-empty
    expect(pageWithSelect.meta.alternatePaths).toBeDefined()

    // AlternatePaths must match homePage alternatePaths
    expect(removeIdsFromArray(pageWithSelect.meta.alternatePaths)).toEqual(
      removeIdsFromArray(pageWithoutSelect.meta.alternatePaths),
    )
  })
})

describe('Find operation gracefully handles missing parent documents.', () => {
  beforeEach(async () => {
    // authors has a non-nullable FK to pages (SQLite/Postgres), so delete it first.
    await deleteCollection('authors')
    await deleteCollection('pages')
  })

  test('findByID logs error and returns doc without virtual fields when parent was deleted', async () => {
    const rootPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Root',
        slug: '',
        content: 'Root',
        isRootPage: true,
        ...virtualFields,
      },
    })

    const childPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Child',
        slug: 'child',
        content: 'Child',
        parent: rootPage.id,
        ...virtualFields,
      },
    })

    // Verify the child has correct virtual fields before deleting the parent
    const childBeforeDeletion = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
    })
    expect(childBeforeDeletion.path).toBe('/de/child')
    expect(childBeforeDeletion.breadcrumbs).toHaveLength(2)

    // Delete the parent directly via the DB adapter (bypassing the preventParentDeletion hook)
    // — the child's parent reference becomes a dangling pointer
    await payload.db.deleteMany({
      collection: 'pages',
      where: { id: { equals: rootPage.id } },
    })

    const loggerErrorSpy = vi.spyOn(payload.logger, 'error')

    // Reading the child should not throw, even though its parent no longer exists
    const result = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
    })

    // Non-virtual fields should still be returned correctly
    expect(result.id).toBe(childPage.id)
    expect(result.title).toBe('Child')
    expect(result.slug).toBe('child')

    if (result.parent === null) {
      // SQLite/Postgres: Payload resolves the dangling reference to null,
      // so the child is treated as a top-level page.
      expect(result.path).toBe('/de/child')
      expect(result.breadcrumbs).toHaveLength(1)
      expect(result.breadcrumbs[0].slug).toBe('child')
    } else {
      // MongoDB: the raw parent ID is retained, the parent lookup fails,
      // and the try-catch logs an error and returns the doc without virtual fields.
      expect(result.parent).toBe(rootPage.id)
      expect(result.path).toBeUndefined()
      expect(result.breadcrumbs).toEqual([])
      expect(loggerErrorSpy).toHaveBeenCalledWith(
        expect.objectContaining({ err: expect.any(Error) }),
        expect.stringContaining('Failed to compute virtual fields for doc'),
      )
    }
  })

  test('find (list) logs error and returns docs without virtual fields when parent was deleted', async () => {
    const rootPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Root',
        slug: '',
        content: 'Root',
        isRootPage: true,
        ...virtualFields,
      },
    })

    await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Child',
        slug: 'child',
        content: 'Child',
        parent: rootPage.id,
        ...virtualFields,
      },
    })

    await payload.db.deleteMany({
      collection: 'pages',
      where: { id: { equals: rootPage.id } },
    })

    const loggerErrorSpy = vi.spyOn(payload.logger, 'error')

    // Using find (list) instead of findByID — should also not throw
    const result = await payload.find({
      collection: 'pages',
      locale: 'de',
    })

    expect(result.docs).toHaveLength(1)
    const child = result.docs[0]
    expect(child.title).toBe('Child')

    if (child.parent === null) {
      // SQLite/Postgres: dangling reference resolved to null, treated as top-level page
      expect(child.path).toBe('/de/child')
      expect(child.breadcrumbs).toHaveLength(1)
    } else {
      // MongoDB: parent ID retained, virtual field computation fails gracefully
      expect(child.path).toBeUndefined()
      expect(child.breadcrumbs).toEqual([])
      expect(loggerErrorSpy).toHaveBeenCalledWith(
        expect.objectContaining({ err: expect.any(Error) }),
        expect.stringContaining('Failed to compute virtual fields for doc'),
      )
    }
  })

  test('deeply nested page handles missing grandparent gracefully', async () => {
    const rootPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Root',
        slug: '',
        content: 'Root',
        isRootPage: true,
        ...virtualFields,
      },
    })

    const parentPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Parent',
        slug: 'parent',
        content: 'Parent',
        parent: rootPage.id,
        ...virtualFields,
      },
    })

    const grandchild = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Grandchild',
        slug: 'grandchild',
        content: 'Grandchild',
        parent: parentPage.id,
        ...virtualFields,
      },
    })

    // Verify correct virtual fields before deletion
    const grandchildBefore = await payload.findByID({
      collection: 'pages',
      id: grandchild.id,
      locale: 'de',
    })
    expect(grandchildBefore.path).toBe('/de/parent/grandchild')
    expect(grandchildBefore.breadcrumbs).toHaveLength(3)

    // Delete the middle parent — the grandchild's parent reference becomes dangling
    await payload.db.deleteMany({
      collection: 'pages',
      where: { id: { equals: parentPage.id } },
    })

    const loggerErrorSpy = vi.spyOn(payload.logger, 'error')

    // Grandchild should still be readable
    const result = await payload.findByID({
      collection: 'pages',
      id: grandchild.id,
      locale: 'de',
    })

    expect(result.id).toBe(grandchild.id)
    expect(result.title).toBe('Grandchild')

    if (result.parent === null) {
      // SQLite/Postgres: dangling reference resolved to null, treated as top-level page
      expect(result.path).toBe('/de/grandchild')
      expect(result.breadcrumbs).toHaveLength(1)
      expect(result.breadcrumbs[0].slug).toBe('grandchild')
    } else {
      // MongoDB: parent ID retained, virtual field computation fails gracefully
      expect(result.parent).toBe(parentPage.id)
      expect(result.path).toBeUndefined()
      expect(result.breadcrumbs).toEqual([])
      expect(loggerErrorSpy).toHaveBeenCalledWith(
        expect.objectContaining({ err: expect.any(Error) }),
        expect.stringContaining('Failed to compute virtual fields for doc'),
      )
    }
  })
})

describe('Slug field behaves as expected for create and update operations', () => {
  beforeEach(async () => {
    // authors has a non-nullable FK to pages (SQLite/Postgres), so delete it first.
    await deleteCollection('authors')
    await deleteCollection('pages')
  })

  test('Slug remains unchanged when title is updated', async () => {
    // Create initial page
    const page = await payload.create({
      collection: 'pages',
      data: {
        title: 'Initial Title',
        content: 'Some content',
        slug: 'initial-title',
        ...virtualFields,
      },
    })

    expect(page.slug).toBe('initial-title')

    // Update the title
    const updatedPage = await payload.update({
      collection: 'pages',
      id: page.id,
      data: {
        title: 'Updated Title',
      },
    })

    // Verify slug remains unchanged
    expect(updatedPage.slug).toBe('initial-title')
    expect(updatedPage.title).toBe('Updated Title')
  })

  test('Validation Error is thrown when creating a page without providing a slug', async () => {
    // Create page without providing a slug - intentionally missing slug to test validation
    try {
      await payload.create({
        collection: 'pages',
        data: {
          title: 'Test Page Title',
          content: 'Some content',
          slug: undefined as unknown as string, // Force missing slug to test validation
          ...virtualFields,
        },
      })
    } catch (error) {
      expect(error).toBeInstanceOf(ValidationError)
    }
  })

  test('Validation Error is thrown when creating a page with an invalid slug', async () => {
    // Create page with invalid slug to test validation
    try {
      await payload.create({
        collection: 'pages',
        data: {
          title: 'Test Page Title 2',
          content: 'Some content 2',
          slug: 'invalid slug &!=',
          ...virtualFields,
        },
      })
    } catch (error) {
      expect(error).toBeInstanceOf(ValidationError)
    }
  })

  test('Validation Error is thrown when trying to create a root page without providing a slug', async () => {
    // Create initial root page without providing a slug - intentionally missing slug to test validation
    try {
      await payload.create({
        collection: 'pages',
        data: {
          title: 'Root Page',
          content: 'Root page content',
          isRootPage: true,
          slug: undefined as unknown as string, // Force missing slug to test validation
          ...virtualFields,
        },
      })
    } catch (error) {
      expect(error).toBeInstanceOf(ValidationError)
    }
  })

  test('Root page is created sucessfully with an empty slug and throws validation error when slug is updated', async () => {
    // Create initial root page with empty slug
    const rootPage = await payload.create({
      collection: 'pages',
      data: {
        title: 'Root Page',
        content: 'Root page content',
        isRootPage: true,
        slug: '',
        ...virtualFields,
      },
    })

    // Verify the slug is empty
    expect(rootPage.slug).toBe('')
    expect(rootPage.isRootPage).toBe(true)

    // Try to update the slug
    try {
      await payload.update({
        collection: 'pages',
        id: rootPage.id,
        data: {
          slug: 'attempted-slug',
        },
      })
    } catch (error) {
      expect(error).toBeInstanceOf(ValidationError)
    }
  })
})

describe('Parent deletion prevention hook', () => {
  beforeEach(async () => await deleteAllCollections(config, ['users']))

  test('prevents deletion when child dependencies exist', async () => {
    // Create parent page
    const parentPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Parent Page',
        slug: 'parent-page-prevents-deletion',
        content: 'Parent content',
        ...virtualFields,
      },
    })

    // Create child page referencing the parent
    await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Child Page',
        slug: 'child-page-prevents-deletion',
        content: 'Child content',
        parent: parentPage.id,
        ...virtualFields,
      },
    })

    // Attempt to delete the parent page - should throw error
    await expect(
      payload.delete({
        collection: 'pages',
        id: parentPage.id,
      }),
    ).rejects.toThrow('Cannot delete this document because it is referenced as a parent by')
  })

  test('allows deletion when no child dependencies exist', async () => {
    // Create parent page
    const parentPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Parent Page',
        slug: 'parent-page-allows-deletion',
        content: 'Parent content',
        ...virtualFields,
      },
    })

    // Create another page without parent reference
    await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Independent Page',
        slug: 'independent-page-allows-deletion',
        content: 'Independent content',
        ...virtualFields,
      },
    })

    // Delete the parent page - should succeed
    const result = await payload.delete({
      collection: 'pages',
      id: parentPage.id,
    })

    // Verify deletion succeeded
    expect(result).toBeTruthy()
    expect(result.id).toBe(parentPage.id)
  })

  test('provides helpful error message with dependency details', async () => {
    // Create parent page
    const parentPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Parent Page',
        slug: 'parent-page',
        content: 'Parent content',
        ...virtualFields,
      },
    })

    // Create multiple child pages
    await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Child Page 1',
        slug: 'child-page-1',
        content: 'Child content 1',
        parent: parentPage.id,
        ...virtualFields,
      },
    })

    await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Child Page 2',
        slug: 'child-page-2',
        content: 'Child content 2',
        parent: parentPage.id,
        ...virtualFields,
      },
    })

    // Attempt to delete parent - should provide detailed error
    try {
      await payload.delete({
        collection: 'pages',
        id: parentPage.id,
      })
      expect.fail('Expected deletion to be prevented')
    } catch (error: unknown) {
      expect((error as Error).message).toContain(
        'Cannot delete this document because it is referenced as a parent by',
      )
      expect((error as Error).message).toContain('2 document(s) in the "pages" collection')
    }
  })

  test('handles multi-collection scenarios', async () => {
    // Create parent page
    const parentPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Parent Page',
        slug: 'parent-page-multi-collection',
        content: 'Parent content',
        ...virtualFields,
      },
    })

    // Create child in pages collection
    await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Child Page',
        slug: 'child-page-multi-collection',
        content: 'Child content',
        parent: parentPage.id,
        ...virtualFields,
      },
    })

    // Attempt to delete parent - should be prevented
    await expect(
      payload.delete({
        collection: 'pages',
        id: parentPage.id,
      }),
    ).rejects.toThrow('Cannot delete this document because it is referenced as a parent by')
  })
})

describe('Virtual fields in findVersions operation', () => {
  beforeEach(async () => {
    // authors has a non-nullable FK to pages (SQLite/Postgres), so delete it first.
    await deleteCollection('authors')
    await deleteCollection('pages')
  })

  test('are correctly set when reading versions', async () => {
    const locale = 'de'
    const pageData = {
      title: 'Test Page',
      slug: 'test-page',
      content: 'Test content',
      ...virtualFields,
    }

    // Create a page
    const page = await payload.create({
      collection: 'pages',
      locale,
      data: pageData,
    })

    // Update the page to create a version
    await payload.update({
      collection: 'pages',
      id: page.id,
      locale,
      data: {
        title: 'Updated Test Page',
      },
    })

    // Get all versions
    const versions = await payload.findVersions({
      collection: 'pages',
      where: {
        parent: {
          equals: page.id,
        },
      },
      select: {},
      locale,
    })

    expect(versions.docs).toBeDefined()
    expect(versions.docs.length).toBeGreaterThan(0)

    // Check that each version has the virtual fields correctly set
    for (const version of versions.docs) {
      expect(version.version).toBeDefined()

      // The path should be correctly generated from the slug
      if (version.version.slug) {
        expect(version.version.path).toBeDefined()
        expect(version.version.path).toBe(`/${locale}/${version.version.slug}`)
      }

      // Breadcrumbs should be correctly generated
      if (version.version.slug) {
        expect(version.version.breadcrumbs).toBeDefined()
        expect(Array.isArray(version.version.breadcrumbs)).toBe(true)
        expect(version.version.breadcrumbs.length).toBeGreaterThan(0)
      }
    }
  })

  test('are correctly set when reading a specific version by ID', async () => {
    const locale = 'de'
    const pageData = {
      title: 'Test Page',
      slug: 'test-page',
      content: 'Test content',
      ...virtualFields,
    }

    // Create a page
    const page = await payload.create({
      collection: 'pages',
      locale,
      data: pageData,
    })

    // Update the page to create a version
    await payload.update({
      collection: 'pages',
      id: page.id,
      locale,
      data: {
        title: 'Updated Test Page for Version',
      },
    })

    // Get all versions to find a specific version ID
    const versions = await payload.findVersions({
      collection: 'pages',
      where: {
        parent: {
          equals: page.id,
        },
      },
      locale,
    })

    expect(versions.docs.length).toBeGreaterThan(0)

    // Get a specific version by ID
    const versionId = versions.docs[0].id
    const version = await payload.findVersionByID({
      collection: 'pages',
      id: versionId,
      locale,
    })

    expect(version).toBeDefined()
    expect(version.version).toBeDefined()

    // The path should be correctly generated from the slug
    if (version.version.slug) {
      expect(version.version.path).toBeDefined()
      expect(version.version.path).toBe(`/${locale}/${version.version.slug}`)

      // Breadcrumbs should be correctly generated
      expect(version.version.breadcrumbs).toBeDefined()
      expect(Array.isArray(version.version.breadcrumbs)).toBe(true)
      expect(version.version.breadcrumbs.length).toBeGreaterThan(0)

      // Verify breadcrumb structure
      const lastBreadcrumb = version.version.breadcrumbs[version.version.breadcrumbs.length - 1]
      expect(lastBreadcrumb.slug).toBe(version.version.slug)
      expect(lastBreadcrumb.path).toBe(version.version.path)
    }
  })

  test('are correctly set when reading a specific version by ID (nested page)', async () => {
    const locale = 'de'
    const parentPageData = {
      title: 'Parent Page',
      slug: 'parent-page',
      content: 'Parent content',
      ...virtualFields,
    }
    const childPageData = {
      title: 'Child Page',
      slug: 'child-page',
      content: 'Child content',
      ...virtualFields,
    }

    // Create parent page
    const parentPage = await payload.create({
      collection: 'pages',
      locale,
      data: parentPageData,
    })

    // Create child page
    const childPage = await payload.create({
      collection: 'pages',
      locale,
      data: { ...childPageData, parent: parentPage.id },
    })

    // Update the child page to create a version
    await payload.update({
      collection: 'pages',
      id: childPage.id,
      locale,
      data: {
        title: 'Updated Child Page',
      },
    })

    // Get versions of the child page
    const versions = await payload.findVersions({
      collection: 'pages',
      where: {
        parent: {
          equals: childPage.id,
        },
      },
      locale,
    })

    expect(versions.docs.length).toBeGreaterThan(0)

    // Check the first version
    const version = versions.docs[0]
    expect(version.version).toBeDefined()

    // The path should include the parent slug
    if (version.version.slug) {
      expect(version.version.path).toBeDefined()
      expect(version.version.path).toBe(`/${locale}/${parentPageData.slug}/${version.version.slug}`)

      // Breadcrumbs should include both parent and child
      expect(version.version.breadcrumbs).toBeDefined()
      expect(Array.isArray(version.version.breadcrumbs)).toBe(true)
      expect(version.version.breadcrumbs.length).toBe(2)

      // Verify parent breadcrumb
      expect(version.version.breadcrumbs[0].slug).toBe(parentPageData.slug)
      expect(version.version.breadcrumbs[0].path).toBe(`/${locale}/${parentPageData.slug}`)

      // Verify child breadcrumb
      expect(version.version.breadcrumbs[1].slug).toBe(version.version.slug)
      expect(version.version.breadcrumbs[1].path).toBe(version.version.path)
    }
  })
})

describe('Select during read operation', () => {
  beforeEach(async () => {
    // clear the collections we use in this test
    await deleteCollection('country-travel-tips')
    await deleteCollection('countries')
    await deleteCollection('pages')
  })

  test('findByID with empty select only returns id', async () => {
    // Create root page
    const rootPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Root Page',
        slug: '',
        content: 'Root content',
        isRootPage: true,
        ...virtualFields,
      },
    })

    // Create child page
    const childPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Child Page',
        slug: 'child-page',
        content: 'Child content',
        parent: rootPage.id,
        ...virtualFields,
      },
    })

    const fetchedWithAllFields = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 0,
    })

    expect(fetchedWithAllFields).toBeDefined()

    // ################ Test empty select depth 0 ################
    const fetchedWithEmptySelect = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 0,
      select: {},
    })

    expect(fetchedWithEmptySelect).toBeDefined()
    expect(Object.keys(fetchedWithEmptySelect)).toEqual(['id']) // has correct fields
    expect(fetchedWithEmptySelect.id).toEqual(fetchedWithAllFields.id) // id is correct

    // ################ Test empty select depth 1 ################
    const fetchedWithEmptySelectDepth1 = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 1,
      select: {},
    })

    expect(fetchedWithEmptySelectDepth1).toBeDefined()
    expect(Object.keys(fetchedWithEmptySelectDepth1)).toEqual(['id']) // has correct fields
    expect(fetchedWithEmptySelectDepth1.id).toEqual(fetchedWithAllFields.id) // id is correct
  })

  test('Respect selection (field: true) of the virtual fields', async () => {
    // Create root page
    const rootPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Root Page',
        slug: '',
        content: 'Root content',
        isRootPage: true,
        ...virtualFields,
      },
    })

    // Create child page
    const childPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Child Page',
        slug: 'child-page',
        content: 'Child content',
        parent: rootPage.id,
        ...virtualFields,
      },
    })

    const fetchedWithAllFields = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 0,
    })

    expect(fetchedWithAllFields).toBeDefined()

    // ################ Test path only ################
    const fetchedWithPath = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 0,
      select: {
        path: true,
      },
    })

    expect(fetchedWithPath).toBeDefined()
    expect(Object.keys(fetchedWithPath)).toContain('path') // has correct fields
    expect(fetchedWithPath.path).toEqual(fetchedWithAllFields.path) // path is correct

    // ################ Test slug only ################
    const fetchedWithSlug = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 0,
      select: {
        slug: true,
      },
    })

    expect(fetchedWithSlug).toBeDefined()
    expect(Object.keys(fetchedWithSlug).sort()).toContain('slug') // has correct fields
    expect(fetchedWithSlug.slug).toEqual(fetchedWithAllFields.slug) // slug is correct

    // ################ Test breadcrumbs only ################
    const fetchedWithBreadcrumbs = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 0,
      select: {
        breadcrumbs: true,
      },
    })

    expect(fetchedWithBreadcrumbs).toBeDefined()
    expect(Object.keys(fetchedWithBreadcrumbs)).toContain('breadcrumbs') // has correct fields
    expect(removeIdsFromArray(fetchedWithBreadcrumbs.breadcrumbs)).toEqual(
      removeIdsFromArray(fetchedWithAllFields.breadcrumbs),
    ) // breadcrumbs is correct

    // ################ Test meta only ################
    const fetchedWithMeta = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 0,
      select: {
        meta: true,
      },
    })

    expect(fetchedWithMeta).toBeDefined()
    expect(Object.keys(fetchedWithMeta).sort()).toContain('meta') // has correct fields
    expect(removeIdsFromArray(fetchedWithMeta.meta.alternatePaths)).toEqual(
      removeIdsFromArray(fetchedWithAllFields.meta.alternatePaths),
    ) // alternatePaths is correct

    // ################ Test meta.alternatePaths only ################
    const fetchedWithMetaAlternatePaths = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 0,
      select: {
        meta: {
          alternatePaths: true,
        },
      },
    })

    expect(fetchedWithMetaAlternatePaths).toBeDefined()
    expect(Object.keys(fetchedWithMetaAlternatePaths).sort()).toContain('meta') // has correct fields
    expect(Object.keys(fetchedWithMetaAlternatePaths.meta).sort()).toContain('alternatePaths') // nested field has correct fields
    expect(removeIdsFromArray(fetchedWithMetaAlternatePaths.meta.alternatePaths)).toEqual(
      removeIdsFromArray(fetchedWithAllFields.meta.alternatePaths),
    ) // alternatePaths is correct
  })

  test('parent relationship field is correctly populated when using select and depth 1', async () => {
    // Create root page
    const rootPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Root Page',
        slug: '',
        content: 'Root content',
        isRootPage: true,
        ...virtualFields,
      },
    })

    // Create child page
    const childPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Child Page',
        slug: 'child-page',
        content: 'Child content',
        parent: rootPage.id,
        ...virtualFields,
      },
    })

    const fetchedWithAllFields = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 1,
    })

    expect(fetchedWithAllFields).toBeDefined()

    const fetchWithPathAndParent = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      // important, set depth to one to populate the parent field
      depth: 1,
      select: {
        path: true,
        parent: true,
      },
    })

    expect(fetchWithPathAndParent).toBeDefined()

    // check if the parent field is still fully populated
    // this test is important because it ensures that the hooks that adjust the selection do not
    // affect nested find calls (populating the parent in this case)
    expect(Object.keys(fetchWithPathAndParent.parent!).sort()).toStrictEqual(
      Object.keys(fetchedWithAllFields.parent!).sort(),
    )
  })

  test('parent relationship field from different collection with different parent field slug is correctly populated when using select and depth 1', async () => {
    // Create countries page in pages collection
    const countriesPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Countries',
        slug: 'countries',
        content: 'Countries content',
        ...virtualFields,
      },
    })

    // Create country page
    const country = await payload.create({
      collection: 'countries',
      locale: 'de',
      data: {
        title: 'Germany',
        slug: 'germany',
        content: 'Country content',
        parent: countriesPage.id,
        ...virtualFields,
      },
    })

    // Create country travel tips page
    const travelTips = await payload.create({
      collection: 'country-travel-tips',
      locale: 'de',
      data: {
        title: 'Travel Tips for Germany',
        slug: 'reisetipps', // Static value for 'de' locale as defined in collection config
        content: 'Travel tips content',
        country: country.id,
        ...virtualFields,
      },
    })

    const fetchedWithAllFields = await payload.findByID({
      collection: 'country-travel-tips',
      id: travelTips.id,
      locale: 'de',
      depth: 1,
    })

    expect(fetchedWithAllFields).toBeDefined()

    const fetchWithPathAndParent = await payload.findByID({
      collection: 'country-travel-tips',
      id: travelTips.id,
      locale: 'de',
      // important, set depth to one to populate the parent (country) field
      depth: 1,
      select: {
        path: true,
        country: true,
      },
    })

    expect(fetchWithPathAndParent).toBeDefined()

    expect(fetchWithPathAndParent.path).toEqual(fetchedWithAllFields.path)

    // check if the parent field is still fully populated
    // this test is important because it ensures that the hooks that adjust the selection do not
    // affect nested find calls (populating the parent in this case)
    expect(Object.keys(fetchWithPathAndParent.country!).sort()).toStrictEqual(
      Object.keys(fetchedWithAllFields.country!).sort(),
    )
  })
})

describe('The afterChange hook doc and previousDoc contain the path of the page.', () => {
  beforeEach(async () => {
    // authors has a non-nullable FK to pages (SQLite/Postgres), so delete it first.
    await deleteCollection('authors')
    await deleteCollection('pages')
    clearCapturedAfterChanges()
  })

  test('doc.path is set on create for a root page.', async () => {
    await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Root Page DE',
        slug: '',
        content: 'Root Page DE',
        isRootPage: true,
        ...virtualFields,
      },
    })

    const { doc } = getLastAfterChangeHookArgs()
    expect(doc.path).toBe('/de')
  })

  test('doc.path is set on create for a nested page.', async () => {
    const rootPageId = (
      await payload.create({
        collection: 'pages',
        locale: 'de',
        data: {
          title: 'Root Page DE',
          slug: 'root-page-de',
          content: 'Root Page DE',
          ...virtualFields,
        },
      })
    ).id

    clearCapturedAfterChanges()

    await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Nested Page DE',
        slug: 'nested-page-de',
        content: 'Nested Page DE',
        parent: rootPageId,
        ...virtualFields,
      },
    })

    const { doc } = getLastAfterChangeHookArgs()
    expect(doc.path).toBe('/de/root-page-de/nested-page-de')
  })

  test('doc.path and previousDoc.path are set on update when slug is unchanged.', async () => {
    const rootPageId = (
      await payload.create({
        collection: 'pages',
        locale: 'de',
        data: {
          title: 'Root Page DE',
          slug: 'root-page-de',
          content: 'Root Page DE',
          ...virtualFields,
        },
      })
    ).id

    clearCapturedAfterChanges()

    await payload.update({
      collection: 'pages',
      id: rootPageId,
      locale: 'de',
      data: {
        title: 'Root Page DE Updated',
      },
    })

    const { doc, previousDoc } = getLastAfterChangeHookArgs()
    expect(doc.path).toBe('/de/root-page-de')
    expect(previousDoc.path).toBe('/de/root-page-de')
  })

  test('previousDoc.path reflects the old path when slug changes.', async () => {
    const pageId = (
      await payload.create({
        collection: 'pages',
        locale: 'de',
        data: {
          title: 'Page DE',
          slug: 'old-slug',
          content: 'Page DE',
          ...virtualFields,
        },
      })
    ).id

    clearCapturedAfterChanges()

    await payload.update({
      collection: 'pages',
      id: pageId,
      locale: 'de',
      data: {
        slug: 'new-slug',
      },
    })

    const { doc, previousDoc } = getLastAfterChangeHookArgs()
    expect(doc.path).toBe('/de/new-slug')
    expect(previousDoc.path).toBe('/de/old-slug')
  })

  test('previousDoc.path reflects the old path when parent changes.', async () => {
    const parentA = (
      await payload.create({
        collection: 'pages',
        locale: 'de',
        data: {
          title: 'Parent A',
          slug: 'parent-a',
          content: 'Parent A',
          ...virtualFields,
        },
      })
    ).id

    const parentB = (
      await payload.create({
        collection: 'pages',
        locale: 'de',
        data: {
          title: 'Parent B',
          slug: 'parent-b',
          content: 'Parent B',
          ...virtualFields,
        },
      })
    ).id

    const childId = (
      await payload.create({
        collection: 'pages',
        locale: 'de',
        data: {
          title: 'Child',
          slug: 'child',
          content: 'Child',
          parent: parentA,
          ...virtualFields,
        },
      })
    ).id

    clearCapturedAfterChanges()

    await payload.update({
      collection: 'pages',
      id: childId,
      locale: 'de',
      data: {
        parent: parentB,
      },
    })

    const { doc, previousDoc } = getLastAfterChangeHookArgs()
    expect(doc.path).toBe('/de/parent-b/child')
    expect(previousDoc.path).toBe('/de/parent-a/child')
  })

  test('paths are correct for deeply nested page slug change.', async () => {
    const grandparentId = (
      await payload.create({
        collection: 'pages',
        locale: 'de',
        data: {
          title: 'Grandparent',
          slug: 'grandparent',
          content: 'Grandparent',
          ...virtualFields,
        },
      })
    ).id

    const parentId = (
      await payload.create({
        collection: 'pages',
        locale: 'de',
        data: {
          title: 'Parent',
          slug: 'parent',
          content: 'Parent',
          parent: grandparentId,
          ...virtualFields,
        },
      })
    ).id

    const childId = (
      await payload.create({
        collection: 'pages',
        locale: 'de',
        data: {
          title: 'Child',
          slug: 'old-child',
          content: 'Child',
          parent: parentId,
          ...virtualFields,
        },
      })
    ).id

    clearCapturedAfterChanges()

    await payload.update({
      collection: 'pages',
      id: childId,
      locale: 'de',
      data: {
        slug: 'new-child',
      },
    })

    const { doc, previousDoc } = getLastAfterChangeHookArgs()
    expect(doc.path).toBe('/de/grandparent/parent/new-child')
    expect(previousDoc.path).toBe('/de/grandparent/parent/old-child')
  })

  test('doc.breadcrumbs is set in afterChange hook.', async () => {
    const parentId = (
      await payload.create({
        collection: 'pages',
        locale: 'de',
        data: {
          title: 'Parent',
          slug: 'parent',
          content: 'Parent',
          ...virtualFields,
        },
      })
    ).id

    clearCapturedAfterChanges()

    await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Child',
        slug: 'child',
        content: 'Child',
        parent: parentId,
        ...virtualFields,
      },
    })

    const { doc } = getLastAfterChangeHookArgs()
    const breadcrumbs = doc.breadcrumbs as Array<{ slug: string; path: string }>
    expect(breadcrumbs).toHaveLength(2)
    expect(breadcrumbs[0].path).toBe('/de/parent')
    expect(breadcrumbs[1].path).toBe('/de/parent/child')
  })

  test('previousDoc.path and doc.path when slug and parent change simultaneously.', async () => {
    const parentA = (
      await payload.create({
        collection: 'pages',
        locale: 'de',
        data: {
          title: 'Parent A',
          slug: 'parent-a',
          content: 'Parent A',
          ...virtualFields,
        },
      })
    ).id

    const parentB = (
      await payload.create({
        collection: 'pages',
        locale: 'de',
        data: {
          title: 'Parent B',
          slug: 'parent-b',
          content: 'Parent B',
          ...virtualFields,
        },
      })
    ).id

    const childId = (
      await payload.create({
        collection: 'pages',
        locale: 'de',
        data: {
          title: 'Child',
          slug: 'old-child',
          content: 'Child',
          parent: parentA,
          ...virtualFields,
        },
      })
    ).id

    clearCapturedAfterChanges()

    await payload.update({
      collection: 'pages',
      id: childId,
      locale: 'de',
      data: {
        slug: 'new-child',
        parent: parentB,
      },
    })

    const { doc, previousDoc } = getLastAfterChangeHookArgs()
    expect(doc.path).toBe('/de/parent-b/new-child')
    expect(previousDoc.path).toBe('/de/parent-a/old-child')
  })

  test('previousDoc has no path when page is newly created.', async () => {
    clearCapturedAfterChanges()

    await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'New Page',
        slug: 'new-page',
        content: 'New Page',
        ...virtualFields,
      },
    })

    const { doc, previousDoc } = getLastAfterChangeHookArgs()
    expect(doc.path).toBe('/de/new-page')
    // On create, previousDoc has no slug so path cannot be computed
    expect(previousDoc.path).toBeUndefined()
  })

  test('logs error for previousDoc but still returns correct doc when previousDoc parent was deleted.', async () => {
    // Create a parent (root page) and a child page under it
    const rootPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Root',
        slug: '',
        content: 'Root',
        isRootPage: true,
        ...virtualFields,
      },
    })

    const childId = (
      await payload.create({
        collection: 'pages',
        locale: 'de',
        data: {
          title: 'Child',
          slug: 'child',
          content: 'Child',
          parent: rootPage.id,
          ...virtualFields,
        },
      })
    ).id

    // Delete the parent directly via the DB adapter (bypassing the preventParentDeletion hook)
    // — the child's parent reference becomes a dangling pointer
    await payload.db.deleteMany({
      collection: 'pages',
      where: { id: { equals: rootPage.id } },
    })

    clearCapturedAfterChanges()
    const loggerErrorSpy = vi.spyOn(payload.logger, 'error')

    // Change parent from rootPage to null. On MongoDB this makes dependentFieldsUnchanged=false,
    // so the afterChange hook computes previousDoc path separately (which will fail
    // because the parent no longer exists in the database).
    const updatedPage = await payload.update({
      collection: 'pages',
      id: childId,
      locale: 'de',
      data: { parent: null },
    })

    // The update operation itself should succeed and return the updated doc
    expect(updatedPage.id).toBe(childId)
    expect(updatedPage.path).toBe('/de/child')
    expect(updatedPage.parent).toBeNull()

    // doc.path should be computed as top-level (no parent)
    const { doc, previousDoc } = getLastAfterChangeHookArgs()
    expect(doc.path).toBe('/de/child')
    expect(doc.breadcrumbs).toHaveLength(1)
    expect(doc.breadcrumbs[0].slug).toBe('child')

    if (previousDoc.parent === null) {
      // SQLite/Postgres: Payload resolves previousDoc.parent to null (dangling reference),
      // so dependentFieldsUnchanged=true and previousDoc reuses doc's virtual fields.
      expect(previousDoc.path).toBe('/de/child')
      expect(previousDoc.breadcrumbs).toHaveLength(1)
    } else {
      // MongoDB: previousDoc retains the raw parent ID. dependentFieldsUnchanged=false,
      // so the hook tries to look up the deleted parent, fails, and logs an error.
      expect(previousDoc.parent).toBe(rootPage.id)
      expect(previousDoc.path).toBeUndefined()
      expect(previousDoc.breadcrumbs).toEqual([])
      expect(loggerErrorSpy).toHaveBeenCalledWith(
        expect.objectContaining({ err: expect.any(Error) }),
        expect.stringContaining('Failed to compute virtual fields for previousDoc'),
      )
      // Only one error should have been logged (for previousDoc, not for doc)
      const virtualFieldErrors = loggerErrorSpy.mock.calls.filter(
        (call) => typeof call[1] === 'string' && call[1].includes('Failed to compute virtual fields'),
      )
      expect(virtualFieldErrors).toHaveLength(1)
    }
  })

  // Note: A test for "doc virtual fields fall back when doc parent was deleted during update"
  // is not possible because Payload's built-in relationship field validation rejects the
  // update before the afterChange hook runs. The doc error path in afterChange is still
  // covered by the beforeRead tests (find/findByID with missing parent).
})

describe('Request-scoped ancestor caching', () => {
  let grandparent: { id: DefaultIDType }
  let parent: { id: DefaultIDType }

  beforeAll(async () => {
    await deleteCollection('pages')

    grandparent = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Grandparent',
        slug: 'grandparent',
        content: 'grandparent',
        ...virtualFields,
      },
    })

    parent = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Parent',
        slug: 'parent',
        content: 'parent',
        parent: grandparent.id,
        ...virtualFields,
      },
    })

    for (const slug of ['child-a', 'child-b', 'child-c']) {
      await payload.create({
        collection: 'pages',
        locale: 'de',
        data: {
          title: slug,
          slug,
          content: slug,
          parent: parent.id,
          ...virtualFields,
        },
      })
    }
  })

  test('shared parent is only fetched once when listing siblings', async () => {
    const findByIDSpy = vi.spyOn(payload, 'findByID')

    await payload.find({
      collection: 'pages',
      locale: 'de',
      where: { parent: { equals: parent.id } },
    })

    const parentFetches = findByIDSpy.mock.calls.filter(
      (call) => call[0].id === parent.id && call[0].collection === 'pages',
    )
    expect(parentFetches).toHaveLength(1)
  })

  test('shared grandparent is only fetched once when listing siblings', async () => {
    const findByIDSpy = vi.spyOn(payload, 'findByID')

    await payload.find({
      collection: 'pages',
      locale: 'de',
      where: { parent: { equals: parent.id } },
    })

    // Each child fetches the parent, which in turn fetches the grandparent for its breadcrumbs.
    // The grandparent should be fetched only once because the cache is passed through via req.context.
    const grandparentFetches = findByIDSpy.mock.calls.filter(
      (call) => call[0].id === grandparent.id && call[0].collection === 'pages',
    )
    expect(grandparentFetches).toHaveLength(1)
  })

  test('virtual fields are still computed correctly despite caching', async () => {
    const result = await payload.find({
      collection: 'pages',
      locale: 'de',
      where: { parent: { equals: parent.id } },
      sort: 'slug',
    })

    expect(result.docs).toHaveLength(3)

    for (const child of result.docs) {
      // Each child should have the full breadcrumb chain: grandparent -> parent -> child
      expect(child.breadcrumbs).toHaveLength(3)
      expect(child.breadcrumbs[0].slug).toBe('grandparent')
      expect(child.breadcrumbs[1].slug).toBe('parent')
      expect(child.path).toBe(`/de/grandparent/parent/${child.slug}`)
    }
  })

  test('different locales are cached separately', async () => {
    // Add English locale to the parent
    await payload.update({
      collection: 'pages',
      id: parent.id,
      locale: 'en',
      data: {
        title: 'Parent EN',
        slug: 'parent-en',
        content: 'parent en',
        parent: grandparent.id,
        ...virtualFields,
      },
    })

    const findByIDSpy = vi.spyOn(payload, 'findByID')

    // Fetch children with locale 'all' — this fetches the parent once per locale
    await payload.find({
      collection: 'pages',
      locale: 'all',
      where: { parent: { equals: parent.id } },
    })

    // The parent should be fetched once for locale 'all' (not once per child)
    const parentFetches = findByIDSpy.mock.calls.filter(
      (call) => call[0].id === parent.id && call[0].collection === 'pages',
    )
    expect(parentFetches).toHaveLength(1)
  })
})

describe('Request context is forwarded to nested findByID calls during breadcrumb computation', () => {
  let parentPage: { id: DefaultIDType }

  beforeAll(async () => {
    await deleteCollection('pages')

    parentPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Context Parent',
        slug: 'context-parent',
        content: 'parent',
        ...virtualFields,
      },
    })
  })

  test('nested findByID receives the full req including user and context', async () => {
    const findByIDSpy = vi.spyOn(payload, 'findByID')

    await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Context Child',
        slug: 'context-child',
        content: 'child',
        parent: parentPage.id,
        ...virtualFields,
      },
    })

    // Find the nested findByID call that fetches the parent during breadcrumb computation
    const parentFetch = findByIDSpy.mock.calls.find(
      (call) => call[0].id === parentPage.id && call[0].collection === 'pages',
    )

    expect(parentFetch).toBeDefined()
    const reqArg = parentFetch![0].req

    // The nested call should receive a req with the payload instance (not a bare object)
    expect(reqArg).toBeDefined()
    expect(reqArg!.payload).toBeDefined()
    expect(reqArg!.transactionID).toBeDefined()

    // The full req should include context (not just the ancestor cache)
    expect(reqArg!.context).toBeDefined()
  })

  test('custom req.context properties are preserved in nested findByID calls', async () => {
    const findByIDSpy = vi.spyOn(payload, 'findByID')

    // Use payload.find with a custom context property
    await payload.find({
      collection: 'pages',
      locale: 'de',
      where: { parent: { equals: parentPage.id } },
      context: { customProperty: 'test-value' },
    })

    // Find the nested findByID call for the parent
    const parentFetch = findByIDSpy.mock.calls.find(
      (call) => call[0].id === parentPage.id && call[0].collection === 'pages',
    )

    expect(parentFetch).toBeDefined()
    const reqArg = parentFetch![0].req

    // The custom context property should be forwarded through to the nested call
    expect(reqArg!.context).toHaveProperty('customProperty', 'test-value')
  })
})

describe('Draft flag is forwarded to parent document fetch during breadcrumb computation', () => {
  let parentPage: { id: DefaultIDType }
  let childPage: { id: DefaultIDType }

  beforeAll(async () => {
    await deleteCollection('pages')

    // Create a published parent page
    parentPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Draft Parent',
        slug: 'draft-parent-published',
        content: 'parent',
        ...virtualFields,
      },
    })

    // Update the parent with a draft version (new slug, not published)
    await payload.update({
      collection: 'pages',
      id: parentPage.id,
      locale: 'de',
      draft: true,
      data: {
        title: 'Draft Parent Updated',
        slug: 'draft-parent-draft',
        content: 'parent updated',
        ...virtualFields,
      },
    })

    // Create a child page referencing the parent
    childPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Draft Child',
        slug: 'draft-child',
        content: 'child',
        parent: parentPage.id,
        ...virtualFields,
      },
    })
  })

  test('draft: true is passed to the parent findByID when draft is in req.query', async () => {
    const findByIDSpy = vi.spyOn(payload, 'findByID')

    // Simulate a REST API request with ?draft=true by passing req.query.draft
    await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      draft: true,
      req: { query: { draft: 'true' } },
    })

    // The inner findByID call for the parent should receive draft: true
    const parentFetch = findByIDSpy.mock.calls.find(
      (call) => call[0].id === parentPage.id && call[0].collection === 'pages',
    )
    expect(parentFetch).toBeDefined()
    expect(parentFetch![0].draft).toBe(true)
  })

  test('no draft flag is passed to the parent findByID when not in draft mode', async () => {
    const findByIDSpy = vi.spyOn(payload, 'findByID')

    // Fetch without draft flag (default non-draft mode)
    await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
    })

    // The inner findByID call for the parent should not have draft: true
    const parentFetch = findByIDSpy.mock.calls.find(
      (call) => call[0].id === parentPage.id && call[0].collection === 'pages',
    )
    expect(parentFetch).toBeDefined()
    expect(parentFetch![0].draft).toBeFalsy()
  })

  test('child breadcrumbs reflect draft parent slug changes when fetched in draft mode', async () => {
    // Fetch child in non-draft mode -> should use the published parent slug
    const childPublished = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
    })

    // Fetch child in draft mode (simulating a REST request with ?draft=true)
    const childDraft = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      draft: true,
      req: { query: { draft: 'true' } },
    })

    // Non-draft mode: parent breadcrumb should use the published slug
    expect(childPublished.breadcrumbs[0].slug).toBe('draft-parent-published')
    expect(childPublished.path).toBe('/de/draft-parent-published/draft-child')

    // Draft mode: parent breadcrumb should reflect the draft parent slug
    expect(childDraft.breadcrumbs[0].slug).toBe('draft-parent-draft')
    expect(childDraft.path).toBe('/de/draft-parent-draft/draft-child')
  })
})

describe('Circular parent reference prevention', () => {
  beforeEach(async () => await deleteAllCollections(config, ['users']))

  test('prevents a document from being set as its own parent', async () => {
    const page = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Self Reference Page',
        slug: 'self-reference-page',
        content: 'Content',
        ...virtualFields,
      },
    })

    await expect(
      payload.update({
        collection: 'pages',
        id: page.id,
        locale: 'de',
        data: {
          parent: page.id,
        },
      }),
    ).rejects.toThrow()
  })

  test('prevents a two-node cycle (A -> B -> A)', async () => {
    const pageA = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Page A',
        slug: 'page-a-cycle',
        content: 'Content A',
        ...virtualFields,
      },
    })

    const pageB = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Page B',
        slug: 'page-b-cycle',
        content: 'Content B',
        parent: pageA.id,
        ...virtualFields,
      },
    })

    // Setting A's parent to B would create a cycle: A -> B -> A
    await expect(
      payload.update({
        collection: 'pages',
        id: pageA.id,
        locale: 'de',
        data: {
          parent: pageB.id,
        },
      }),
    ).rejects.toThrow()
  })

  test('prevents a deep cycle (A -> B -> C -> A)', async () => {
    const pageA = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Page A Deep',
        slug: 'page-a-deep',
        content: 'Content A',
        ...virtualFields,
      },
    })

    const pageB = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Page B Deep',
        slug: 'page-b-deep',
        content: 'Content B',
        parent: pageA.id,
        ...virtualFields,
      },
    })

    const pageC = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Page C Deep',
        slug: 'page-c-deep',
        content: 'Content C',
        parent: pageB.id,
        ...virtualFields,
      },
    })

    // Setting A's parent to C would create a cycle: A -> B -> C -> A
    await expect(
      payload.update({
        collection: 'pages',
        id: pageA.id,
        locale: 'de',
        data: {
          parent: pageC.id,
        },
      }),
    ).rejects.toThrow()
  })

  test('allows setting a valid (non-circular) parent', async () => {
    const parentPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Valid Parent',
        slug: 'valid-parent',
        content: 'Parent content',
        ...virtualFields,
      },
    })

    const childPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Valid Child',
        slug: 'valid-child',
        content: 'Child content',
        ...virtualFields,
      },
    })

    const result = await payload.update({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      data: {
        parent: parentPage.id,
      },
    })

    expect(result.id).toBe(childPage.id)
  })
})

/**
 * Helper function to remove id field from objects in an array
 */
const removeIdsFromArray = <T extends { id?: any; [key: string]: any }>(
  array: T[],
): Omit<T, 'id'>[] => {
  return array.map(({ id, ...rest }) => rest)
}

/**
 * Helper function to delete all documents from a collection.
 */
const deleteCollection = async (collection: CollectionSlug) => {
  // use db.deleteMany instead of payload.delete to avoid running hooks
  await payload.db.deleteMany({
    collection: collection,
    where: {},
  })

  // this will fail for collections which have no versions enabled, therefore wrapped in a try catch
  try {
    await payload.db.deleteVersions({
      collection: collection,
      where: {},
    })
  } catch {}
}

/**
 * Deletion order for collections to respect foreign key constraints.
 * Collections are deleted in this order: children before parents.
 * Collections not in this list will be deleted at the end in arbitrary order.
 */
const COLLECTION_DELETION_ORDER: CollectionSlug[] = [
  // Level 3: deepest nested (depends on level 2)
  'country-travel-tips',
  // Level 2: depends on level 1 collections
  'blogposts',
  'authors',
  'countries',
  // Level 1: root collections (pages can self-reference)
  'pages',
  // Level 0: no dependencies
  'blogpost-categories',
  'redirects',
]

const deleteAllCollections = async (
  config: Promise<SanitizedConfig>,
  except: CollectionSlug[] = [],
) => {
  const collections = (await config).collections?.filter((c) => !except.includes(c.slug)) ?? []
  const collectionSlugs = new Set(collections.map((c) => c.slug))

  // Delete in the specified order first
  for (const slug of COLLECTION_DELETION_ORDER) {
    if (collectionSlugs.has(slug)) {
      await deleteCollection(slug)
      collectionSlugs.delete(slug)
    }
  }

  // Delete any remaining collections not in the order list
  for (const slug of Array.from(collectionSlugs)) {
    await deleteCollection(slug)
  }
}
