import payload, { CollectionSlug, SanitizedConfig, ValidationError } from 'payload'
import { afterAll, beforeAll, beforeEach, describe, expect, test } from 'vitest'
import config from './src/payload.config'
import type { Config } from 'payload/generated-types'

type DefaultIDType = Config['db']['defaultIDType']

/**
 * Empty virtual fields that are generated by the plugin.
 * Spread this into data objects when creating documents to satisfy TypeScript.
 */
const virtualFields = {
  breadcrumbs: [],
  meta: { alternatePaths: [] },
  path: '',
}

beforeAll(async () => {
  await payload.init({
    config: config,
  })

  // clear all collections except users
  await deleteAllCollections(config, ['users'])
})

afterAll(async () => {
  await deleteAllCollections(config)

  if (payload.db && typeof payload.db.destroy === 'function') {
    await payload.db.destroy()
  } else {
    console.log('Could not destroy database')
  }
})

describe('Path and breadcrumb virtual fields are returned correctly for find operation.', () => {
  describe('The root page document', () => {
    beforeEach(async () => await deleteCollection('pages'))

    test('has the correct virtual fields when only one locale is present', async () => {
      const locale = 'de'
      const rootPageData = {
        title: 'Root Page DE',
        slug: '',
        content: 'Root Page DE',
        isRootPage: true,
        ...virtualFields,
      }

      const rootPageId = (
        await payload.create({
          collection: 'pages',
          locale,
          data: rootPageData,
        })
      ).id

      const rootPage = await payload.findByID({
        collection: 'pages',
        id: rootPageId,
        locale: locale,
      })

      const path = `/${locale}`

      expect(rootPage.slug).toBe('') // Plugin convention: The slug of the root page is an empty string.
      expect(rootPage.path).toBe(path)
      expect(removeIdsFromArray(rootPage.breadcrumbs)).toEqual(
        removeIdsFromArray([
          {
            id: undefined,
            path,
            label: rootPageData.title,
            slug: rootPageData.slug,
          },
        ]),
      )
      expect(removeIdsFromArray(rootPage.meta?.alternatePaths)).toEqual(
        removeIdsFromArray([
          {
            id: undefined,
            hreflang: locale,
            path,
          },
        ]),
      )
    })

    test('has the correct virtual fields when all locales are present', async () => {
      const rootPageDataDe = {
        title: 'Root Page DE',
        slug: '',
        content: 'Root Page DE',
        isRootPage: true,
        ...virtualFields,
      }
      const rootPageDataEn = {
        title: 'Root Page EN',
        slug: '',
        content: 'Root Page EN',
        isRootPage: true,
        ...virtualFields,
      }

      const rootPageId = (
        await payload.create({
          collection: 'pages',
          locale: 'de',
          data: rootPageDataDe,
        })
      ).id

      await payload.update({
        collection: 'pages',
        id: rootPageId,
        locale: 'en',
        data: rootPageDataEn,
      })

      const rootPage = await payload.findByID({
        collection: 'pages',
        id: rootPageId,
        locale: 'all',
      })

      expect(rootPage.slug).toEqual({
        de: '',
        en: '',
      })
      expect(rootPage.path).toEqual({
        de: '/de',
        en: '/en',
      })

      // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
      expect(removeIdsFromArray(rootPage.breadcrumbs.de)).toEqual(
        removeIdsFromArray([
          {
            path: '/de',
            label: rootPageDataDe.title,
            slug: rootPageDataDe.slug,
          },
        ]),
      )
      // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
      expect(removeIdsFromArray(rootPage.breadcrumbs.en)).toEqual(
        removeIdsFromArray([
          {
            path: '/en',
            label: rootPageDataEn.title,
            slug: rootPageDataEn.slug,
          },
        ]),
      )
      expect(removeIdsFromArray(rootPage.meta.alternatePaths)).toEqual(
        removeIdsFromArray([
          {
            hreflang: 'de',
            path: '/de',
          },
          {
            hreflang: 'en',
            path: '/en',
          },
        ]),
      )
    })
  })

  describe('Nested document in same collection with all locales created.', () => {
    const rootPageDataDe = {
      title: 'Root Page DE',
      slug: 'root-page-de',
      content: 'Root Page DE',
    }
    const rootPageDataEn = {
      title: 'Root Page EN',
      slug: 'root-page-en',
      content: 'Root Page EN',
    }
    const nestedPageDataDe = {
      title: 'Nested Page DE',
      slug: 'nested-page-de',
      content: 'Nested Page DE',
    }
    const nestedPageDataEn = {
      title: 'Nested Page EN',
      slug: 'nested-page-en',
      content: 'Nested Page EN',
    }
    let rootPageId: DefaultIDType | undefined
    let nestedPageId: DefaultIDType | undefined

    beforeAll(async () => {
      await deleteCollection('pages')

      // ################# Seed the database for the tests of this group #################

      rootPageId = (
        await payload.create({
          collection: 'pages',
          locale: 'de',
          data: { ...rootPageDataDe, ...virtualFields },
        })
      ).id

      await payload.update({
        collection: 'pages',
        id: rootPageId,
        locale: 'en',
        data: { ...rootPageDataEn, ...virtualFields },
      })

      nestedPageId = (
        await payload.create({
          collection: 'pages',
          locale: 'de',
          data: { ...nestedPageDataDe, parent: rootPageId, ...virtualFields },
        })
      ).id

      await payload.update({
        collection: 'pages',
        id: nestedPageId,
        locale: 'en',
        data: { ...nestedPageDataEn, parent: rootPageId, ...virtualFields },
      })
    })

    describe('Breadcrumbs', () => {
      test('All locales requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'all',
        })

        expect(nestedPage).toBeDefined()

        // Breadcrumbs must be an object containing the breadcrumbs for all locales
        expect(typeof nestedPage.breadcrumbs).toBe('object')

        // Breadcrumbs must be correctly set
        expect(nestedPage.breadcrumbs).toStrictEqual({
          de: [
            {
              // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
              id: nestedPage.breadcrumbs.de[0]?.id,
              label: rootPageDataDe.title,
              slug: rootPageDataDe.slug,
              path: `/de/${rootPageDataDe.slug}`,
            },
            {
              // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
              id: nestedPage.breadcrumbs.de[1]?.id,
              label: nestedPageDataDe.title,
              slug: nestedPageDataDe.slug,
              path: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
            },
          ],
          en: [
            {
              // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
              id: nestedPage.breadcrumbs.en[0]?.id,
              label: rootPageDataEn.title,
              slug: rootPageDataEn.slug,
              path: `/en/${rootPageDataEn.slug}`,
            },
            {
              // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
              id: nestedPage.breadcrumbs.en[1]?.id,
              label: nestedPageDataEn.title,
              slug: nestedPageDataEn.slug,
              path: `/en/${rootPageDataEn.slug}/${nestedPageDataEn.slug}`,
            },
          ],
        })
      })

      test('One locale requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'de',
        })

        expect(nestedPage).toBeDefined()

        // Breadcrumbs must be an object containing the breadcrumbs for all locales
        expect(Array.isArray(nestedPage.breadcrumbs)).toBe(true)

        // Breadcrumbs must be correctly set
        expect(nestedPage.breadcrumbs).toStrictEqual([
          {
            id: nestedPage.breadcrumbs[0].id,
            label: rootPageDataDe.title,
            slug: rootPageDataDe.slug,
            path: `/de/${rootPageDataDe.slug}`,
          },
          {
            id: nestedPage.breadcrumbs[1].id,
            label: nestedPageDataDe.title,
            slug: nestedPageDataDe.slug,
            path: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
          },
        ])
      })
    })

    describe('Path', () => {
      test('All locales requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'all',
        })

        expect(nestedPage).toBeDefined()
        expect(nestedPage.path).toBeDefined()
        expect(typeof nestedPage.path).toBe('object')

        expect(nestedPage.path).toStrictEqual({
          de: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
          en: `/en/${rootPageDataEn.slug}/${nestedPageDataEn.slug}`,
        })
      })

      test('One locale requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'de',
        })

        expect(nestedPage).toBeDefined()
        expect(nestedPage.path).toBeDefined()
        expect(typeof nestedPage.path).toBe('string')

        expect(nestedPage.path).toStrictEqual(`/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`)
      })
    })

    describe('AlternatePaths', () => {
      test('All locales requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'all',
        })

        expect(nestedPage).toBeDefined()
        expect(nestedPage.meta.alternatePaths).toBeDefined()
        expect(Array.isArray(nestedPage.meta.alternatePaths)).toBe(true)

        expect(removeIdsFromArray(nestedPage.meta.alternatePaths)).toStrictEqual([
          {
            hreflang: 'de',
            path: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
          },
          {
            hreflang: 'en',
            path: `/en/${rootPageDataEn.slug}/${nestedPageDataEn.slug}`,
          },
        ])
      })

      test('One locale requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'de',
        })

        expect(nestedPage).toBeDefined()
        expect(nestedPage.meta.alternatePaths).toBeDefined()
        expect(Array.isArray(nestedPage.meta.alternatePaths)).toBe(true)

        expect(removeIdsFromArray(nestedPage.meta.alternatePaths)).toStrictEqual(
          removeIdsFromArray([
            {
              hreflang: 'de',
              path: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
            },
            {
              hreflang: 'en',
              path: `/en/${rootPageDataEn.slug}/${nestedPageDataEn.slug}`,
            },
          ]),
        )
      })
    })
  })

  describe('Nested document in same collection with one locale created.', () => {
    const rootPageDataDe = {
      title: 'Root Page DE',
      slug: 'root-page-de-one-locale',
      content: 'Root Page DE',
    }
    const nestedPageDataDe = {
      title: 'Nested Page DE',
      slug: 'nested-page-de-one-locale',
      content: 'Nested Page DE',
    }
    let rootPageId: DefaultIDType | undefined
    let nestedPageId: DefaultIDType | undefined

    beforeAll(async () => {
      await deleteCollection('pages')

      // ################# Seed the database for the tests of this group #################

      rootPageId = (
        await payload.create({
          collection: 'pages',
          locale: 'de',
          data: { ...rootPageDataDe, ...virtualFields },
        })
      ).id

      nestedPageId = (
        await payload.create({
          collection: 'pages',
          locale: 'de',
          data: { ...nestedPageDataDe, parent: rootPageId, ...virtualFields },
        })
      ).id
    })

    describe('Breadcrumbs', () => {
      test('All locales requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'all',
        })

        expect(nestedPage).toBeDefined()

        // Breadcrumbs must be an object containing the breadcrumbs for all locales
        expect(typeof nestedPage.breadcrumbs).toBe('object')

        // Breadcrumbs must be correctly set
        expect(nestedPage.breadcrumbs).toStrictEqual({
          de: [
            {
              // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
              id: nestedPage.breadcrumbs.de[0]?.id,
              label: rootPageDataDe.title,
              slug: rootPageDataDe.slug,
              path: `/de/${rootPageDataDe.slug}`,
            },
            {
              // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
              id: nestedPage.breadcrumbs.de[1]?.id,
              label: nestedPageDataDe.title,
              slug: nestedPageDataDe.slug,
              path: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
            },
          ],
          // TODO: After revising the implementation, change this to be undefined
          // Note: When the doc is not defined in en, the plugin should not return breadcrumbs for en!
          en: [
            {
              // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
              id: nestedPage.breadcrumbs.en[0]?.id,
              label: undefined,
              path: '/en',
              slug: undefined,
            },
            {
              // @ts-expect-error - Payload does not type find operations with locale='all' correctly yet.
              id: nestedPage.breadcrumbs.en[1]?.id,
              label: undefined,
              path: '/en',
              slug: undefined,
            },
          ],
        })
      })

      test('One locale requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'de',
        })

        expect(nestedPage).toBeDefined()

        // Breadcrumbs must be an object containing the breadcrumbs for all locales
        expect(Array.isArray(nestedPage.breadcrumbs)).toBe(true)

        // Breadcrumbs must be correctly set
        expect(nestedPage.breadcrumbs).toStrictEqual([
          {
            id: nestedPage.breadcrumbs[0].id,
            label: rootPageDataDe.title,
            slug: rootPageDataDe.slug,
            path: `/de/${rootPageDataDe.slug}`,
          },
          {
            id: nestedPage.breadcrumbs[1].id,
            label: nestedPageDataDe.title,
            slug: nestedPageDataDe.slug,
            path: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
          },
        ])
      })
    })

    describe('Path', () => {
      test('All locales requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'all',
        })

        expect(nestedPage).toBeDefined()
        expect(nestedPage.path).toBeDefined()
        expect(typeof nestedPage.path).toBe('object')

        expect(nestedPage.path).toStrictEqual({
          de: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
        })
      })

      test('One locale requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'de',
        })

        expect(nestedPage).toBeDefined()
        expect(nestedPage.path).toBeDefined()
        expect(typeof nestedPage.path).toBe('string')

        expect(nestedPage.path).toStrictEqual(`/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`)
      })
    })

    describe('AlternatePaths', () => {
      test('All locales requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'all',
        })

        expect(nestedPage).toBeDefined()
        expect(nestedPage.meta.alternatePaths).toBeDefined()
        expect(Array.isArray(nestedPage.meta.alternatePaths)).toBe(true)

        expect(removeIdsFromArray(nestedPage.meta.alternatePaths)).toStrictEqual(
          removeIdsFromArray([
            {
              hreflang: 'de',
              path: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
            },
          ]),
        )
      })

      test('One locale requested.', async () => {
        const nestedPage = await payload.findByID({
          collection: 'pages',
          id: nestedPageId!,
          locale: 'de',
        })

        expect(nestedPage).toBeDefined()
        expect(nestedPage.meta.alternatePaths).toBeDefined()
        expect(Array.isArray(nestedPage.meta.alternatePaths)).toBe(true)

        expect(removeIdsFromArray(nestedPage.meta.alternatePaths)).toStrictEqual(
          removeIdsFromArray([
            {
              hreflang: 'de',
              path: `/de/${rootPageDataDe.slug}/${nestedPageDataDe.slug}`,
            },
          ]),
        )
      })
    })
  })

  test('Nested document across collections with one locale created.', async () => {
    const locale = 'de'
    const authorOverviewPageData = {
      title: 'Authors',
      slug: 'authors',
      content: 'Authors page',
    }
    const authorPageData = {
      name: 'Test Author',
      slug: 'test-author',
      content: 'Test Author',
    }

    const authorOverviewPageId = (
      await payload.create({
        collection: 'pages',
        locale,
        data: { ...authorOverviewPageData, ...virtualFields },
      })
    ).id

    const authorPageId = (
      await payload.create({
        collection: 'authors',
        locale,
        data: { ...authorPageData, parent: authorOverviewPageId, ...virtualFields },
      })
    ).id

    // Verify the author was created and linked correctly
    const author = await payload.findByID({
      collection: 'authors',
      depth: 0,
      id: authorPageId,
    })

    expect(author).toBeDefined()
    expect(author.parent).toBe(authorOverviewPageId)

    // Verify path is correctly set
    expect(author.path).toBe(`/${locale}/${authorOverviewPageData.slug}/${authorPageData.slug}`)

    // Verify breadcrumbs are correctly set
    expect(author.breadcrumbs).toBeDefined()
    expect(removeIdsFromArray(author.breadcrumbs)).toEqual([
      {
        label: authorOverviewPageData.title,
        path: `/${locale}/${authorOverviewPageData.slug}`,
        slug: authorOverviewPageData.slug,
      },
      {
        label: authorPageData.name,
        path: `/${locale}/${authorOverviewPageData.slug}/${authorPageData.slug}`,
        slug: authorPageData.slug,
      },
    ])

    // Verify alternatePaths are correctly set
    expect(author.meta.alternatePaths).toBeDefined()
    expect(removeIdsFromArray(author.meta.alternatePaths)).toEqual(
      removeIdsFromArray([
        {
          hreflang: locale,
          path: `/${locale}/${authorOverviewPageData.slug}/${authorPageData.slug}`,
        },
      ]),
    )
  })
})

describe('Path and breadcrumb virtual fields are set correctly for find operation with select.', () => {
  test('Only path and breadcrumbs are selected (not slug etc.)', async () => {
    const pageId = (
      await payload.create({
        collection: 'pages',
        locale: 'de',
        data: {
          title: 'Page DE',
          slug: 'page',
          content: 'Page DE',
          ...virtualFields,
        },
      })
    ).id

    const pageWithSelect = await payload.findByID({
      collection: 'pages',
      id: pageId,
      select: {
        path: true,
        breadcrumbs: true,
        meta: {
          alternatePaths: true,
        },
      },
    })

    const pageWithoutSelect = await payload.findByID({
      collection: 'pages',
      id: pageId,
    })

    // Breadcrumbs must be an array
    expect(Array.isArray(pageWithSelect.breadcrumbs)).toBe(true)

    // Breadcrumbs array should match homePage breadcrumbs
    expect(removeIdsFromArray(pageWithSelect.breadcrumbs)).toEqual(
      removeIdsFromArray(pageWithoutSelect.breadcrumbs),
    )

    // Path must be defined and non-empty
    expect(pageWithSelect.path).toBeDefined()

    // Path must be defined and non-empty
    expect(pageWithSelect.path).toEqual(pageWithoutSelect.path)

    // AlternatePaths must be defined and non-empty
    expect(pageWithSelect.meta.alternatePaths).toBeDefined()

    // AlternatePaths must match homePage alternatePaths
    expect(removeIdsFromArray(pageWithSelect.meta.alternatePaths)).toEqual(
      removeIdsFromArray(pageWithoutSelect.meta.alternatePaths),
    )
  })
})

describe('Slug field behaves as expected for create and update operations', () => {
  test('Slug remains unchanged when title is updated', async () => {
    // Create initial page
    const page = await payload.create({
      collection: 'pages',
      data: {
        title: 'Initial Title',
        content: 'Some content',
        slug: 'initial-title',
        ...virtualFields,
      },
    })

    expect(page.slug).toBe('initial-title')

    // Update the title
    const updatedPage = await payload.update({
      collection: 'pages',
      id: page.id,
      data: {
        title: 'Updated Title',
      },
    })

    // Verify slug remains unchanged
    expect(updatedPage.slug).toBe('initial-title')
    expect(updatedPage.title).toBe('Updated Title')
  })

  test('Validation Error is thrown when creating a page without providing a slug', async () => {
    // Create page without providing a slug - intentionally missing slug to test validation
    try {
      await payload.create({
        collection: 'pages',
        data: {
          title: 'Test Page Title',
          content: 'Some content',
          slug: undefined as unknown as string, // Force missing slug to test validation
          ...virtualFields,
        },
      })
    } catch (error) {
      expect(error).toBeInstanceOf(ValidationError)
    }
  })

  test('Validation Error is thrown when creating a page with an invalid slug', async () => {
    // Create page with invalid slug to test validation
    try {
      await payload.create({
        collection: 'pages',
        data: {
          title: 'Test Page Title 2',
          content: 'Some content 2',
          slug: 'invalid slug &!=',
          ...virtualFields,
        },
      })
    } catch (error) {
      expect(error).toBeInstanceOf(ValidationError)
    }
  })

  test('Validation Error is thrown when trying to create a root page without providing a slug', async () => {
    // Create initial root page without providing a slug - intentionally missing slug to test validation
    try {
      await payload.create({
        collection: 'pages',
        data: {
          title: 'Root Page',
          content: 'Root page content',
          isRootPage: true,
          slug: undefined as unknown as string, // Force missing slug to test validation
          ...virtualFields,
        },
      })
    } catch (error) {
      expect(error).toBeInstanceOf(ValidationError)
    }
  })

  test('Root page is created sucessfully with an empty slug and throws validation error when slug is updated', async () => {
    // Create initial root page with empty slug
    const rootPage = await payload.create({
      collection: 'pages',
      data: {
        title: 'Root Page',
        content: 'Root page content',
        isRootPage: true,
        slug: '',
        ...virtualFields,
      },
    })

    // Verify the slug is empty
    expect(rootPage.slug).toBe('')
    expect(rootPage.isRootPage).toBe(true)

    // Try to update the slug
    try {
      await payload.update({
        collection: 'pages',
        id: rootPage.id,
        data: {
          slug: 'attempted-slug',
        },
      })
    } catch (error) {
      expect(error).toBeInstanceOf(ValidationError)
    }
  })
})

describe('Parent deletion prevention hook', () => {
  beforeEach(async () => await deleteAllCollections(config, ['users']))

  test('prevents deletion when child dependencies exist', async () => {
    // Create parent page
    const parentPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Parent Page',
        slug: 'parent-page-prevents-deletion',
        content: 'Parent content',
        ...virtualFields,
      },
    })

    // Create child page referencing the parent
    await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Child Page',
        slug: 'child-page-prevents-deletion',
        content: 'Child content',
        parent: parentPage.id,
        ...virtualFields,
      },
    })

    // Attempt to delete the parent page - should throw error
    await expect(
      payload.delete({
        collection: 'pages',
        id: parentPage.id,
      }),
    ).rejects.toThrow('Cannot delete this document because it is referenced as a parent by')
  })

  test('allows deletion when no child dependencies exist', async () => {
    // Create parent page
    const parentPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Parent Page',
        slug: 'parent-page-allows-deletion',
        content: 'Parent content',
        ...virtualFields,
      },
    })

    // Create another page without parent reference
    await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Independent Page',
        slug: 'independent-page-allows-deletion',
        content: 'Independent content',
        ...virtualFields,
      },
    })

    // Delete the parent page - should succeed
    const result = await payload.delete({
      collection: 'pages',
      id: parentPage.id,
    })

    // Verify deletion succeeded
    expect(result).toBeTruthy()
    expect(result.id).toBe(parentPage.id)
  })

  test('provides helpful error message with dependency details', async () => {
    // Create parent page
    const parentPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Parent Page',
        slug: 'parent-page',
        content: 'Parent content',
        ...virtualFields,
      },
    })

    // Create multiple child pages
    await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Child Page 1',
        slug: 'child-page-1',
        content: 'Child content 1',
        parent: parentPage.id,
        ...virtualFields,
      },
    })

    await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Child Page 2',
        slug: 'child-page-2',
        content: 'Child content 2',
        parent: parentPage.id,
        ...virtualFields,
      },
    })

    // Attempt to delete parent - should provide detailed error
    try {
      await payload.delete({
        collection: 'pages',
        id: parentPage.id,
      })
      expect.fail('Expected deletion to be prevented')
    } catch (error: unknown) {
      expect((error as Error).message).toContain(
        'Cannot delete this document because it is referenced as a parent by',
      )
      expect((error as Error).message).toContain('2 document(s) in the "pages" collection')
    }
  })

  test('handles multi-collection scenarios', async () => {
    // Create parent page
    const parentPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Parent Page',
        slug: 'parent-page-multi-collection',
        content: 'Parent content',
        ...virtualFields,
      },
    })

    // Create child in pages collection
    await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Child Page',
        slug: 'child-page-multi-collection',
        content: 'Child content',
        parent: parentPage.id,
        ...virtualFields,
      },
    })

    // Attempt to delete parent - should be prevented
    await expect(
      payload.delete({
        collection: 'pages',
        id: parentPage.id,
      }),
    ).rejects.toThrow('Cannot delete this document because it is referenced as a parent by')
  })
})

describe('Select during read operation', () => {
  beforeEach(async () => {
    // clear the collections we use in this test
    await deleteCollection('country-travel-tips')
    await deleteCollection('countries')
    await deleteCollection('pages')
  })

  test('findByID with empty select only returns id', async () => {
    // Create root page
    const rootPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Root Page',
        slug: '',
        content: 'Root content',
        isRootPage: true,
        ...virtualFields,
      },
    })

    // Create child page
    const childPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Child Page',
        slug: 'child-page',
        content: 'Child content',
        parent: rootPage.id,
        ...virtualFields,
      },
    })

    const fetchedWithAllFields = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 0,
    })

    expect(fetchedWithAllFields).toBeDefined()

    // ################ Test empty select depth 0 ################
    const fetchedWithEmptySelect = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 0,
      select: {},
    })

    expect(fetchedWithEmptySelect).toBeDefined()
    expect(Object.keys(fetchedWithEmptySelect)).toEqual(['id']) // has correct fields
    expect(fetchedWithEmptySelect.id).toEqual(fetchedWithAllFields.id) // id is correct

    // ################ Test empty select depth 1 ################
    const fetchedWithEmptySelectDepth1 = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 1,
      select: {},
    })

    expect(fetchedWithEmptySelectDepth1).toBeDefined()
    expect(Object.keys(fetchedWithEmptySelectDepth1)).toEqual(['id']) // has correct fields
    expect(fetchedWithEmptySelectDepth1.id).toEqual(fetchedWithAllFields.id) // id is correct
  })

  test('Respect selection (field: true) of the virtual fields', async () => {
    // Create root page
    const rootPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Root Page',
        slug: '',
        content: 'Root content',
        isRootPage: true,
        ...virtualFields,
      },
    })

    // Create child page
    const childPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Child Page',
        slug: 'child-page',
        content: 'Child content',
        parent: rootPage.id,
        ...virtualFields,
      },
    })

    const fetchedWithAllFields = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 0,
    })

    expect(fetchedWithAllFields).toBeDefined()

    // ################ Test path only ################
    const fetchedWithPath = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 0,
      select: {
        path: true,
      },
    })

    expect(fetchedWithPath).toBeDefined()
    expect(Object.keys(fetchedWithPath)).toContain('path') // has correct fields
    expect(fetchedWithPath.path).toEqual(fetchedWithAllFields.path) // path is correct

    // ################ Test slug only ################
    const fetchedWithSlug = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 0,
      select: {
        slug: true,
      },
    })

    expect(fetchedWithSlug).toBeDefined()
    expect(Object.keys(fetchedWithSlug).sort()).toContain('slug') // has correct fields
    expect(fetchedWithSlug.slug).toEqual(fetchedWithAllFields.slug) // slug is correct

    // ################ Test breadcrumbs only ################
    const fetchedWithBreadcrumbs = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 0,
      select: {
        breadcrumbs: true,
      },
    })

    expect(fetchedWithBreadcrumbs).toBeDefined()
    expect(Object.keys(fetchedWithBreadcrumbs)).toContain('breadcrumbs') // has correct fields
    expect(removeIdsFromArray(fetchedWithBreadcrumbs.breadcrumbs)).toEqual(
      removeIdsFromArray(fetchedWithAllFields.breadcrumbs),
    ) // breadcrumbs is correct

    // ################ Test meta only ################
    const fetchedWithMeta = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 0,
      select: {
        meta: true,
      },
    })

    expect(fetchedWithMeta).toBeDefined()
    expect(Object.keys(fetchedWithMeta).sort()).toContain('meta') // has correct fields
    expect(removeIdsFromArray(fetchedWithMeta.meta.alternatePaths)).toEqual(
      removeIdsFromArray(fetchedWithAllFields.meta.alternatePaths),
    ) // alternatePaths is correct

    // ################ Test meta.alternatePaths only ################
    const fetchedWithMetaAlternatePaths = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 0,
      select: {
        meta: {
          alternatePaths: true,
        },
      },
    })

    expect(fetchedWithMetaAlternatePaths).toBeDefined()
    expect(Object.keys(fetchedWithMetaAlternatePaths).sort()).toContain('meta') // has correct fields
    expect(Object.keys(fetchedWithMetaAlternatePaths.meta).sort()).toContain('alternatePaths') // nested field has correct fields
    expect(removeIdsFromArray(fetchedWithMetaAlternatePaths.meta.alternatePaths)).toEqual(
      removeIdsFromArray(fetchedWithAllFields.meta.alternatePaths),
    ) // alternatePaths is correct
  })

  test('parent relationship field is correctly populated when using select and depth 1', async () => {
    // Create root page
    const rootPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Root Page',
        slug: '',
        content: 'Root content',
        isRootPage: true,
        ...virtualFields,
      },
    })

    // Create child page
    const childPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Child Page',
        slug: 'child-page',
        content: 'Child content',
        parent: rootPage.id,
        ...virtualFields,
      },
    })

    const fetchedWithAllFields = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      depth: 1,
    })

    expect(fetchedWithAllFields).toBeDefined()

    const fetchWithPathAndParent = await payload.findByID({
      collection: 'pages',
      id: childPage.id,
      locale: 'de',
      // important, set depth to one to populate the parent field
      depth: 1,
      select: {
        path: true,
        parent: true,
      },
    })

    expect(fetchWithPathAndParent).toBeDefined()

    // check if the parent field is still fully populated
    // this test is important because it ensures that the hooks that adjust the selection do not
    // affect nested find calls (populating the parent in this case)
    expect(Object.keys(fetchWithPathAndParent.parent!).sort()).toStrictEqual(
      Object.keys(fetchedWithAllFields.parent!).sort(),
    )
  })

  test('parent relationship field from different collection with different parent field slug is correctly populated when using select and depth 1', async () => {
    // Create countries page in pages collection
    const countriesPage = await payload.create({
      collection: 'pages',
      locale: 'de',
      data: {
        title: 'Countries',
        slug: 'countries',
        content: 'Countries content',
        ...virtualFields,
      },
    })

    // Create country page
    const country = await payload.create({
      collection: 'countries',
      locale: 'de',
      data: {
        title: 'Germany',
        slug: 'germany',
        content: 'Country content',
        parent: countriesPage.id,
        ...virtualFields,
      },
    })

    // Create country travel tips page
    const travelTips = await payload.create({
      collection: 'country-travel-tips',
      locale: 'de',
      data: {
        title: 'Travel Tips for Germany',
        slug: 'reisetipps', // Static value for 'de' locale as defined in collection config
        content: 'Travel tips content',
        country: country.id,
        ...virtualFields,
      },
    })

    const fetchedWithAllFields = await payload.findByID({
      collection: 'country-travel-tips',
      id: travelTips.id,
      locale: 'de',
      depth: 1,
    })

    expect(fetchedWithAllFields).toBeDefined()

    const fetchWithPathAndParent = await payload.findByID({
      collection: 'country-travel-tips',
      id: travelTips.id,
      locale: 'de',
      // important, set depth to one to populate the parent (country) field
      depth: 1,
      select: {
        path: true,
        country: true,
      },
    })

    expect(fetchWithPathAndParent).toBeDefined()

    expect(fetchWithPathAndParent.path).toEqual(fetchedWithAllFields.path)

    // check if the parent field is still fully populated
    // this test is important because it ensures that the hooks that adjust the selection do not
    // affect nested find calls (populating the parent in this case)
    expect(Object.keys(fetchWithPathAndParent.country!).sort()).toStrictEqual(
      Object.keys(fetchedWithAllFields.country!).sort(),
    )
  })
})

/**
 * Helper function to remove id field from objects in an array
 */
const removeIdsFromArray = <T extends { id?: any; [key: string]: any }>(
  array: T[],
): Omit<T, 'id'>[] => {
  return array.map(({ id, ...rest }) => rest)
}

/**
 * Helper function to delete all documents from a collection.
 */
const deleteCollection = async (collection: CollectionSlug) => {
  // use db.deleteMany instead of payload.delete to avoid running hooks
  await payload.db.deleteMany({
    collection: collection,
    where: {},
  })

  // this will fail for collections which have no versions enabled, therefore wrapped in a try catch
  try {
    await payload.db.deleteVersions({
      collection: collection,
      where: {},
    })
  } catch {}
}

/**
 * Deletion order for collections to respect foreign key constraints.
 * Collections are deleted in this order: children before parents.
 * Collections not in this list will be deleted at the end in arbitrary order.
 */
const COLLECTION_DELETION_ORDER: CollectionSlug[] = [
  // Level 3: deepest nested (depends on level 2)
  'country-travel-tips',
  // Level 2: depends on level 1 collections
  'blogposts',
  'authors',
  'countries',
  // Level 1: root collections (pages can self-reference)
  'pages',
  // Level 0: no dependencies
  'blogpost-categories',
  'redirects',
]

const deleteAllCollections = async (
  config: Promise<SanitizedConfig>,
  except: CollectionSlug[] = [],
) => {
  const collections = (await config).collections?.filter((c) => !except.includes(c.slug)) ?? []
  const collectionSlugs = new Set(collections.map((c) => c.slug))

  // Delete in the specified order first
  for (const slug of COLLECTION_DELETION_ORDER) {
    if (collectionSlugs.has(slug)) {
      await deleteCollection(slug)
      collectionSlugs.delete(slug)
    }
  }

  // Delete any remaining collections not in the order list
  for (const slug of Array.from(collectionSlugs)) {
    await deleteCollection(slug)
  }
}
