// DO NOT MODIFY. This file is automatically generated.
// Generated for database: sqlite

import { sqliteAdapter } from '@payloadcms/db-sqlite'

export const databaseAdapter = sqliteAdapter({
  client: {
    url: process.env.SQLITE_URL!,
  },
  // The sqlite adapter runs without transactions unless this is set. The plugin's guards read
  // uncommitted state of the write they guard, so the tests need real transactions.
  transactionOptions: {},
})
