// DO NOT MODIFY. This file is automatically generated.
// Generated for database: sqlite

import { sqliteAdapter } from '@payloadcms/db-sqlite'

export const databaseAdapter = sqliteAdapter({
  client: {
    url: process.env.SQLITE_URL!,
  },
})

