// DO NOT MODIFY. This file is automatically generated.
// Generated for database: mongodb

import { mongooseAdapter } from '@payloadcms/db-mongodb'

export const databaseAdapter = mongooseAdapter({
  url: process.env.MONGODB_URL!,
})

