import payload, { CollectionSlug } from 'payload'
import { afterAll, beforeAll, beforeEach, describe, expect, test } from 'vitest'
import { clearPathCache, findPageByPath, resolvePagePath } from '@jhb.software/payload-pages-plugin'
import config from './src/payload.config'
import type { Config } from 'payload/generated-types'

type DefaultIDType = Config['db']['defaultIDType']

/**
 * Empty virtual fields that are generated by the plugin.
 * Spread this into data objects when creating documents to satisfy TypeScript.
 */
const virtualFields = {
  breadcrumbs: [],
  meta: { alternatePaths: [] },
  path: '',
}

/** Collections deleted in this order (children before parents) to respect foreign key constraints. */
const COLLECTION_DELETION_ORDER: CollectionSlug[] = [
  'country-travel-tips',
  'blogposts',
  'authors',
  'countries',
  'pages',
  'blogpost-categories',
  'redirects',
]

beforeAll(async () => {
  await payload.init({
    config: config,
  })

  for (const collection of COLLECTION_DELETION_ORDER) {
    await deleteCollection(collection)
  }
})

afterAll(async () => {
  if (payload.db && typeof payload.db.destroy === 'function') {
    await payload.db.destroy()
  }
})

beforeEach(async () => {
  await deleteCollection('pages')
  await clearPathCache(payload)
})

/** Returns all KV keys written by the pages plugin path cache. */
const pathCacheKeys = async () =>
  (await payload.kv.keys()).filter((key) => key.startsWith('payload-pages:'))

const createPage = async (data: {
  title: string
  slug: string
  parent?: DefaultIDType
  isRootPage?: boolean
}) => {
  return await payload.create({
    collection: 'pages',
    data: {
      content: data.title,
      // payload.create only publishes when _status is explicitly set
      _status: 'published' as const,
      ...data,
      ...virtualFields,
    },
  })
}

describe('findPageByPath in an unlocalized config', () => {
  test('resolves a nested page by its path', async () => {
    const parent = await createPage({ title: 'Parent', slug: 'parent' })
    const child = await createPage({ title: 'Child', slug: 'child', parent: parent.id })

    const result = await findPageByPath({ payload, path: '/parent/child' })

    expect(result?.collection).toBe('pages')
    expect(result?.doc.id).toBe(child.id)
    expect(result?.doc.path).toBe('/parent/child')
  })

  test('resolves the root page via the root path', async () => {
    const rootPage = await createPage({ title: 'Root', slug: '', isRootPage: true })

    const result = await findPageByPath({ payload, path: '/' })

    expect(result?.doc.id).toBe(rootPage.id)
    expect(result?.doc.path).toBe('/')
  })

  test('returns null for a path that matches no page', async () => {
    expect(await findPageByPath({ payload, path: '/unknown' })).toBeNull()
  })

  test('resolvePagePath returns the collection, id and path of the page', async () => {
    const page = await createPage({ title: 'Parent', slug: 'parent' })

    expect(await resolvePagePath({ payload, path: '/parent' })).toEqual({
      collection: 'pages',
      id: page.id,
      path: '/parent',
    })
  })
})

describe('Path cache disabled via the pathCache plugin config option', () => {
  test('does not write cache entries by default', async () => {
    await createPage({ title: 'Parent', slug: 'parent' })

    const result = await findPageByPath({ payload, path: '/parent' })

    expect(result).not.toBeNull()
    expect(await pathCacheKeys()).toHaveLength(0)
  })

  test('the per-call cache argument overrides the plugin config', async () => {
    await createPage({ title: 'Parent', slug: 'parent' })

    const result = await findPageByPath({ payload, path: '/parent', cache: true })

    expect(result).not.toBeNull()
    expect(await pathCacheKeys()).toHaveLength(1)
  })
})

/**
 * Helper function to delete all documents from a collection.
 */
const deleteCollection = async (collection: CollectionSlug) => {
  // use db.deleteMany instead of payload.delete to avoid running hooks
  await payload.db.deleteMany({
    collection: collection,
    where: {},
  })

  // this will fail for collections which have no versions enabled, therefore wrapped in a try catch
  try {
    await payload.db.deleteVersions({
      collection: collection,
      where: {},
    })
  } catch {}
}
