import payload, { createLocalReq } from 'payload'
import { afterAll, beforeAll, beforeEach, describe, expect, test } from 'vitest'
import { listPagePaths } from '@jhb.software/payload-pages-plugin'
import config from './src/payload.config'
import type { Config } from 'payload/generated-types'
import {
  clearPathChangeRecords,
  recordedPathChangeErrors,
  recordedPathChanges,
} from './src/test/pathChangesCapture'

type DefaultIDType = Config['db']['defaultIDType']

/**
 * Empty virtual fields that are generated by the plugin.
 * Spread this into data objects when creating documents to satisfy TypeScript.
 */
const virtualFields = {
  breadcrumbs: [],
  path: '',
}

beforeAll(async () => {
  await payload.init({ config })
})

afterAll(async () => {
  if (payload.db && typeof payload.db.destroy === 'function') {
    await payload.db.destroy()
  }
})

const createPage = async (data: {
  title: string
  slug: string
  parent?: DefaultIDType
  _status?: 'draft' | 'published'
}) =>
  await payload.create({
    collection: 'pages',
    data: { content: 'Content', _status: 'published', ...virtualFields, ...data },
  })

describe('path index on an unlocalized install', () => {
  beforeEach(async () => {
    await payload.db.deleteMany({ collection: 'pages', where: {} })
    await payload.db.deleteVersions({ collection: 'pages', where: {} })
    clearPathChangeRecords()
  })

  test('listPagePaths entries omit the locale member', async () => {
    await createPage({ title: 'Home Section', slug: 'home-section' })

    const entries = await listPagePaths({ req: await createLocalReq({}, payload) })

    expect(entries.map((entry) => entry.path)).toEqual(['/home-section'])
    expect(entries[0].locale).toBeUndefined()
    expect('locale' in entries[0]).toBe(false)
  })

  test('a rename produces exactly one entry per document rather than one per locale', async () => {
    const parent = await createPage({ title: 'Parent', slug: 'parent' })
    const child = await createPage({ title: 'Child', slug: 'child', parent: parent.id })

    clearPathChangeRecords()
    await payload.update({
      collection: 'pages',
      id: parent.id,
      data: { slug: 'parent-renamed', _status: 'published' },
    })

    expect(recordedPathChangeErrors()).toEqual([])
    const changes = recordedPathChanges()
    const byId = new Map(changes.map((change) => [change.id, change]))

    expect(changes).toHaveLength(2)
    expect(byId.get(parent.id)).toMatchObject({ previousPath: '/parent', path: '/parent-renamed' })
    expect(byId.get(child.id)).toMatchObject({
      previousPath: '/parent/child',
      path: '/parent-renamed/child',
    })
    expect(changes.every((change) => !('locale' in change) || change.locale === undefined)).toBe(
      true,
    )
  })

  test('with preventParentDeletion disabled, hard-deleting a parent returns entries for its descendants', async () => {
    const parent = await createPage({ title: 'Doomed Parent', slug: 'doomed-parent' })
    const child = await createPage({
      title: 'Doomed Child',
      slug: 'doomed-child',
      parent: parent.id,
    })

    clearPathChangeRecords()
    // this app disables the guard, so no skip key is needed
    await payload.delete({ collection: 'pages', id: parent.id })

    expect(recordedPathChangeErrors()).toEqual([])
    const changes = recordedPathChanges()
    const byId = new Map(changes.map((change) => [change.id, change]))

    expect(changes).toHaveLength(2)
    expect(byId.get(parent.id)).toMatchObject({ previousPath: '/doomed-parent', path: null })
    expect(byId.get(child.id)).toMatchObject({
      previousPath: '/doomed-parent/doomed-child',
      path: null,
    })
  })
})
