import type { FlattenedField, SelectType } from 'payload'

import { getSelectMode } from 'payload/shared'

/** The virtual fields the plugin generates. */
export const virtualFieldNames = ['path', 'breadcrumbs', 'meta']

/** Whether the collection has the `meta.alternatePaths` field the plugin fills. */
function hasAlternatePathsField(fields: FlattenedField[]): boolean {
  const meta = fields.find((field) => field.name === 'meta')
  return (
    !!meta &&
    'flattenedFields' in meta &&
    meta.flattenedFields.some((field) => field.name === 'alternatePaths')
  )
}

/**
 * Checks if any of the virtual fields generated by the plugin is selected, based on the select object.
 *
 * `meta` is only a group holding `alternatePaths` (next to the SEO plugin's own fields), so the
 * select is followed into it. A collection without the `alternatePaths` field has no virtual
 * field there at all.
 * @param select The select object
 * @param fields The flattened fields of the collection
 * @returns true if at least one virtual field is selected, false otherwise
 */
export function hasVirtualFieldSelected(
  select: SelectType | undefined,
  fields: FlattenedField[],
): boolean {
  if (!select) {
    return false
  }

  const include = getSelectMode(select) === 'include'
  // A nested select (e.g. `{ breadcrumbs: { label: false } }`) keeps the field itself.
  const isSelected = (value: unknown) => (include ? !!value : value !== false)

  if (isSelected(select.path) || isSelected(select.breadcrumbs)) {
    return true
  }

  if (!hasAlternatePathsField(fields)) {
    return false
  }

  const meta = select.meta
  return typeof meta === 'object' ? isSelected(meta.alternatePaths) : isSelected(meta)
}
