import type { CollectionConfig } from 'payload'

import { alternatePathsField } from '@jhb.software/payload-pages-plugin'

export const Authors: CollectionConfig = {
  slug: 'authors',
  admin: {
    useAsTitle: 'name',
  },
  custom: {
    pagesPlugin: {
      page: {
        parent: {
          collection: 'pages',
          name: 'parent',
          sharedDocument: true,
        },
        breadcrumbs: {
          labelField: 'name',
        },
        // Example: a collection where preview and live preview are disabled:
        livePreview: false,
        preview: false,
      },
    },
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
      localized: true,
    },
    {
      name: 'content',
      type: 'textarea',
      required: true,
      localized: true,
    },
    {
      // normally this group would be generated by the seo plugin
      name: 'meta',
      type: 'group',
      fields: [alternatePathsField()],
    },
  ],
}
