import type { CollectionConfig } from 'payload'

import { alternatePathsField } from '@jhb.software/payload-pages-plugin'

export const CountryTravelTips: CollectionConfig = {
  slug: 'country-travel-tips',
  admin: {
    useAsTitle: 'title',
  },
  custom: {
    pagesPlugin: {
      page: {
        parent: {
          collection: 'countries',
          name: 'country',
        },
        slug: {
          unique: false,
          staticValue: {
            de: 'reisetipps',
            en: 'travel-tips',
          },
        },
      },
    },
  },
  versions: {
    drafts: {
      autosave: true,
    },
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
      localized: true,
    },
    {
      name: 'content',
      type: 'textarea',
      required: true,
      localized: true,
    },
    {
      // normally this group would be generated by the seo plugin
      name: 'meta',
      type: 'group',
      fields: [alternatePathsField()],
    },
  ],
}
