import { alternatePathsField, PageCollectionConfig } from '@jhb.software/payload-pages-plugin'
import { captureAfterChangeDoc } from '../test/afterChangeCapture'
import { countCollectionAfterRead, countFieldAfterRead } from '../test/hookExecutionCounter'

export const Pages: PageCollectionConfig = {
  slug: 'pages',
  access: {
    read: ({ req }) => (req.context as Record<string, unknown>)?.restrictPageAccess !== true,
  },
  admin: {
    useAsTitle: 'title',
  },
  hooks: {
    afterChange: [captureAfterChangeDoc],
    afterRead: [countCollectionAfterRead],
  },
  page: {
    parent: {
      collection: 'pages',
      name: 'parent',
    },
    isRootCollection: true,
  },
  versions: {
    drafts: true,
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
      localized: true,
      hooks: {
        afterRead: [countFieldAfterRead('title')],
      },
    },
    {
      name: 'content',
      type: 'textarea',
      required: true,
      localized: true,
      hooks: {
        afterRead: [countFieldAfterRead('content')],
      },
    },
    {
      // normally this group would be generated by the seo plugin
      name: 'meta',
      type: 'group',
      fields: [
        {
          name: 'title',
          type: 'text',
        },
        {
          name: 'description',
          type: 'text',
        },
        alternatePathsField(),
      ],
    },
  ],
}
