import { alternatePathsField, PageCollectionConfig } from '@jhb.software/payload-pages-plugin'
import { captureAfterChangeDoc } from '../test/afterChangeCapture'

export const Pages: PageCollectionConfig = {
  slug: 'pages',
  access: {
    read: ({ req }) => (req.context as Record<string, unknown>)?.restrictPageAccess !== true,
  },
  admin: {
    useAsTitle: 'title',
  },
  hooks: {
    afterChange: [captureAfterChangeDoc],
  },
  page: {
    parent: {
      collection: 'pages',
      name: 'parent',
    },
    isRootCollection: true,
  },
  versions: {
    drafts: true,
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
      localized: true,
    },
    {
      name: 'content',
      type: 'textarea',
      required: true,
      localized: true,
    },
    {
      // normally this group would be generated by the seo plugin
      name: 'meta',
      type: 'group',
      fields: [alternatePathsField()],
    },
  ],
}
