packages:
  - './'
  - 'dev/astro/'
  - 'dev/payload/'
allowBuilds:
  esbuild: true
  sharp: true
  '@swc/core': true

overrides:
  dompurify: '^3.4.13'
  prettier: '3.9.6'
  next: '16.3.0'
  esbuild: '^0.28.1'
